/**
 *
 *  MBiodata.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "MBiodata.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::db_hospital;

const std::string MBiodata::Cols::_id = "id";
const std::string MBiodata::Cols::_fullname = "fullname";
const std::string MBiodata::Cols::_mobile_phone = "mobile_phone";
const std::string MBiodata::Cols::_image = "image";
const std::string MBiodata::Cols::_image_path = "image_path";
const std::string MBiodata::Cols::_created_by = "created_by";
const std::string MBiodata::Cols::_created_on = "created_on";
const std::string MBiodata::Cols::_modified_by = "modified_by";
const std::string MBiodata::Cols::_modified_on = "modified_on";
const std::string MBiodata::Cols::_deleted_by = "deleted_by";
const std::string MBiodata::Cols::_deleted_on = "deleted_on";
const std::string MBiodata::Cols::_is_delete = "is_delete";
const std::string MBiodata::primaryKeyName = "id";
const bool MBiodata::hasPrimaryKey = true;
const std::string MBiodata::tableName = "m_biodata";

const std::vector<typename MBiodata::MetaData> MBiodata::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"fullname","std::string","character varying",255,0,0,0},
{"mobile_phone","std::string","character varying",15,0,0,0},
{"image","std::vector<char>","bytea",0,0,0,0},
{"image_path","std::string","character varying",255,0,0,0},
{"created_by","int64_t","bigint",8,0,0,1},
{"created_on","::trantor::Date","timestamp without time zone",0,0,0,1},
{"modified_by","int64_t","bigint",8,0,0,0},
{"modified_on","::trantor::Date","timestamp without time zone",0,0,0,0},
{"deleted_by","int64_t","bigint",8,0,0,0},
{"deleted_on","::trantor::Date","timestamp without time zone",0,0,0,0},
{"is_delete","bool","boolean",1,0,0,1}
};
const std::string &MBiodata::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
MBiodata::MBiodata(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["fullname"].isNull())
        {
            fullname_=std::make_shared<std::string>(r["fullname"].as<std::string>());
        }
        if(!r["mobile_phone"].isNull())
        {
            mobilePhone_=std::make_shared<std::string>(r["mobile_phone"].as<std::string>());
        }
        if(!r["image"].isNull())
        {
            auto str = r["image"].as<std::string_view>();
            if(str.length()>=2&&
                str[0]=='\\'&&str[1]=='x')
            {
                image_=std::make_shared<std::vector<char>>(drogon::utils::hexToBinaryVector(str.data()+2,str.length()-2));
            }
        }
        if(!r["image_path"].isNull())
        {
            imagePath_=std::make_shared<std::string>(r["image_path"].as<std::string>());
        }
        if(!r["created_by"].isNull())
        {
            createdBy_=std::make_shared<int64_t>(r["created_by"].as<int64_t>());
        }
        if(!r["created_on"].isNull())
        {
            auto timeStr = r["created_on"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["modified_by"].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>(r["modified_by"].as<int64_t>());
        }
        if(!r["modified_on"].isNull())
        {
            auto timeStr = r["modified_on"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["deleted_by"].isNull())
        {
            deletedBy_=std::make_shared<int64_t>(r["deleted_by"].as<int64_t>());
        }
        if(!r["deleted_on"].isNull())
        {
            auto timeStr = r["deleted_on"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["is_delete"].isNull())
        {
            isDelete_=std::make_shared<bool>(r["is_delete"].as<bool>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 12 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            fullname_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            mobilePhone_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto str = r[index].as<std::string_view>();
            if(str.length()>=2&&
                str[0]=='\\'&&str[1]=='x')
            {
                image_=std::make_shared<std::vector<char>>(drogon::utils::hexToBinaryVector(str.data()+2,str.length()-2));
            }
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            imagePath_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            createdBy_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            deletedBy_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            isDelete_=std::make_shared<bool>(r[index].as<bool>());
        }
    }

}

MBiodata::MBiodata(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 12)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            fullname_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            mobilePhone_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto str = pJson[pMasqueradingVector[3]].asString();
            image_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            imagePath_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson[pMasqueradingVector[11]].asBool());
        }
    }
}

MBiodata::MBiodata(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("fullname"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["fullname"].isNull())
        {
            fullname_=std::make_shared<std::string>(pJson["fullname"].asString());
        }
    }
    if(pJson.isMember("mobile_phone"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["mobile_phone"].isNull())
        {
            mobilePhone_=std::make_shared<std::string>(pJson["mobile_phone"].asString());
        }
    }
    if(pJson.isMember("image"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["image"].isNull())
        {
            auto str = pJson["image"].asString();
            image_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(pJson.isMember("image_path"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["image_path"].isNull())
        {
            imagePath_=std::make_shared<std::string>(pJson["image_path"].asString());
        }
    }
    if(pJson.isMember("created_by"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["created_by"].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson["created_by"].asInt64());
        }
    }
    if(pJson.isMember("created_on"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["created_on"].isNull())
        {
            auto timeStr = pJson["created_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("modified_by"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["modified_by"].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson["modified_by"].asInt64());
        }
    }
    if(pJson.isMember("modified_on"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["modified_on"].isNull())
        {
            auto timeStr = pJson["modified_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("deleted_by"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["deleted_by"].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson["deleted_by"].asInt64());
        }
    }
    if(pJson.isMember("deleted_on"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["deleted_on"].isNull())
        {
            auto timeStr = pJson["deleted_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("is_delete"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["is_delete"].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson["is_delete"].asBool());
        }
    }
}

void MBiodata::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 12)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            fullname_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            mobilePhone_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto str = pJson[pMasqueradingVector[3]].asString();
            image_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            imagePath_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson[pMasqueradingVector[11]].asBool());
        }
    }
}

void MBiodata::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("fullname"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["fullname"].isNull())
        {
            fullname_=std::make_shared<std::string>(pJson["fullname"].asString());
        }
    }
    if(pJson.isMember("mobile_phone"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["mobile_phone"].isNull())
        {
            mobilePhone_=std::make_shared<std::string>(pJson["mobile_phone"].asString());
        }
    }
    if(pJson.isMember("image"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["image"].isNull())
        {
            auto str = pJson["image"].asString();
            image_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(pJson.isMember("image_path"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["image_path"].isNull())
        {
            imagePath_=std::make_shared<std::string>(pJson["image_path"].asString());
        }
    }
    if(pJson.isMember("created_by"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["created_by"].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson["created_by"].asInt64());
        }
    }
    if(pJson.isMember("created_on"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["created_on"].isNull())
        {
            auto timeStr = pJson["created_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("modified_by"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["modified_by"].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson["modified_by"].asInt64());
        }
    }
    if(pJson.isMember("modified_on"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["modified_on"].isNull())
        {
            auto timeStr = pJson["modified_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("deleted_by"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["deleted_by"].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson["deleted_by"].asInt64());
        }
    }
    if(pJson.isMember("deleted_on"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["deleted_on"].isNull())
        {
            auto timeStr = pJson["deleted_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("is_delete"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["is_delete"].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson["is_delete"].asBool());
        }
    }
}

const int64_t &MBiodata::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MBiodata::getId() const noexcept
{
    return id_;
}
void MBiodata::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename MBiodata::PrimaryKeyType & MBiodata::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &MBiodata::getValueOfFullname() const noexcept
{
    static const std::string defaultValue = std::string();
    if(fullname_)
        return *fullname_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MBiodata::getFullname() const noexcept
{
    return fullname_;
}
void MBiodata::setFullname(const std::string &pFullname) noexcept
{
    fullname_ = std::make_shared<std::string>(pFullname);
    dirtyFlag_[1] = true;
}
void MBiodata::setFullname(std::string &&pFullname) noexcept
{
    fullname_ = std::make_shared<std::string>(std::move(pFullname));
    dirtyFlag_[1] = true;
}
void MBiodata::setFullnameToNull() noexcept
{
    fullname_.reset();
    dirtyFlag_[1] = true;
}

const std::string &MBiodata::getValueOfMobilePhone() const noexcept
{
    static const std::string defaultValue = std::string();
    if(mobilePhone_)
        return *mobilePhone_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MBiodata::getMobilePhone() const noexcept
{
    return mobilePhone_;
}
void MBiodata::setMobilePhone(const std::string &pMobilePhone) noexcept
{
    mobilePhone_ = std::make_shared<std::string>(pMobilePhone);
    dirtyFlag_[2] = true;
}
void MBiodata::setMobilePhone(std::string &&pMobilePhone) noexcept
{
    mobilePhone_ = std::make_shared<std::string>(std::move(pMobilePhone));
    dirtyFlag_[2] = true;
}
void MBiodata::setMobilePhoneToNull() noexcept
{
    mobilePhone_.reset();
    dirtyFlag_[2] = true;
}

const std::vector<char> &MBiodata::getValueOfImage() const noexcept
{
    static const std::vector<char> defaultValue = std::vector<char>();
    if(image_)
        return *image_;
    return defaultValue;
}
std::string MBiodata::getValueOfImageAsString() const noexcept
{
    static const std::string defaultValue = std::string();
    if(image_)
        return std::string(image_->data(),image_->size());
    return defaultValue;
}
const std::shared_ptr<std::vector<char>> &MBiodata::getImage() const noexcept
{
    return image_;
}
void MBiodata::setImage(const std::vector<char> &pImage) noexcept
{
    image_ = std::make_shared<std::vector<char>>(pImage);
    dirtyFlag_[3] = true;
}
void MBiodata::setImage(const std::string &pImage) noexcept
{
    image_ = std::make_shared<std::vector<char>>(pImage.c_str(),pImage.c_str()+pImage.length());
    dirtyFlag_[3] = true;
}
void MBiodata::setImageToNull() noexcept
{
    image_.reset();
    dirtyFlag_[3] = true;
}

const std::string &MBiodata::getValueOfImagePath() const noexcept
{
    static const std::string defaultValue = std::string();
    if(imagePath_)
        return *imagePath_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MBiodata::getImagePath() const noexcept
{
    return imagePath_;
}
void MBiodata::setImagePath(const std::string &pImagePath) noexcept
{
    imagePath_ = std::make_shared<std::string>(pImagePath);
    dirtyFlag_[4] = true;
}
void MBiodata::setImagePath(std::string &&pImagePath) noexcept
{
    imagePath_ = std::make_shared<std::string>(std::move(pImagePath));
    dirtyFlag_[4] = true;
}
void MBiodata::setImagePathToNull() noexcept
{
    imagePath_.reset();
    dirtyFlag_[4] = true;
}

const int64_t &MBiodata::getValueOfCreatedBy() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(createdBy_)
        return *createdBy_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MBiodata::getCreatedBy() const noexcept
{
    return createdBy_;
}
void MBiodata::setCreatedBy(const int64_t &pCreatedBy) noexcept
{
    createdBy_ = std::make_shared<int64_t>(pCreatedBy);
    dirtyFlag_[5] = true;
}

const ::trantor::Date &MBiodata::getValueOfCreatedOn() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdOn_)
        return *createdOn_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &MBiodata::getCreatedOn() const noexcept
{
    return createdOn_;
}
void MBiodata::setCreatedOn(const ::trantor::Date &pCreatedOn) noexcept
{
    createdOn_ = std::make_shared<::trantor::Date>(pCreatedOn);
    dirtyFlag_[6] = true;
}

const int64_t &MBiodata::getValueOfModifiedBy() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(modifiedBy_)
        return *modifiedBy_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MBiodata::getModifiedBy() const noexcept
{
    return modifiedBy_;
}
void MBiodata::setModifiedBy(const int64_t &pModifiedBy) noexcept
{
    modifiedBy_ = std::make_shared<int64_t>(pModifiedBy);
    dirtyFlag_[7] = true;
}
void MBiodata::setModifiedByToNull() noexcept
{
    modifiedBy_.reset();
    dirtyFlag_[7] = true;
}

const ::trantor::Date &MBiodata::getValueOfModifiedOn() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(modifiedOn_)
        return *modifiedOn_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &MBiodata::getModifiedOn() const noexcept
{
    return modifiedOn_;
}
void MBiodata::setModifiedOn(const ::trantor::Date &pModifiedOn) noexcept
{
    modifiedOn_ = std::make_shared<::trantor::Date>(pModifiedOn);
    dirtyFlag_[8] = true;
}
void MBiodata::setModifiedOnToNull() noexcept
{
    modifiedOn_.reset();
    dirtyFlag_[8] = true;
}

const int64_t &MBiodata::getValueOfDeletedBy() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(deletedBy_)
        return *deletedBy_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MBiodata::getDeletedBy() const noexcept
{
    return deletedBy_;
}
void MBiodata::setDeletedBy(const int64_t &pDeletedBy) noexcept
{
    deletedBy_ = std::make_shared<int64_t>(pDeletedBy);
    dirtyFlag_[9] = true;
}
void MBiodata::setDeletedByToNull() noexcept
{
    deletedBy_.reset();
    dirtyFlag_[9] = true;
}

const ::trantor::Date &MBiodata::getValueOfDeletedOn() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(deletedOn_)
        return *deletedOn_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &MBiodata::getDeletedOn() const noexcept
{
    return deletedOn_;
}
void MBiodata::setDeletedOn(const ::trantor::Date &pDeletedOn) noexcept
{
    deletedOn_ = std::make_shared<::trantor::Date>(pDeletedOn);
    dirtyFlag_[10] = true;
}
void MBiodata::setDeletedOnToNull() noexcept
{
    deletedOn_.reset();
    dirtyFlag_[10] = true;
}

const bool &MBiodata::getValueOfIsDelete() const noexcept
{
    static const bool defaultValue = bool();
    if(isDelete_)
        return *isDelete_;
    return defaultValue;
}
const std::shared_ptr<bool> &MBiodata::getIsDelete() const noexcept
{
    return isDelete_;
}
void MBiodata::setIsDelete(const bool &pIsDelete) noexcept
{
    isDelete_ = std::make_shared<bool>(pIsDelete);
    dirtyFlag_[11] = true;
}

void MBiodata::updateId(const uint64_t id)
{
}

const std::vector<std::string> &MBiodata::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "fullname",
        "mobile_phone",
        "image",
        "image_path",
        "created_by",
        "created_on",
        "modified_by",
        "modified_on",
        "deleted_by",
        "deleted_on",
        "is_delete"
    };
    return inCols;
}

void MBiodata::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getFullname())
        {
            binder << getValueOfFullname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMobilePhone())
        {
            binder << getValueOfMobilePhone();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getImage())
        {
            binder << getValueOfImage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getImagePath())
        {
            binder << getValueOfImagePath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCreatedBy())
        {
            binder << getValueOfCreatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreatedOn())
        {
            binder << getValueOfCreatedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getModifiedBy())
        {
            binder << getValueOfModifiedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getModifiedOn())
        {
            binder << getValueOfModifiedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getDeletedBy())
        {
            binder << getValueOfDeletedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getDeletedOn())
        {
            binder << getValueOfDeletedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getIsDelete())
        {
            binder << getValueOfIsDelete();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> MBiodata::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    return ret;
}

void MBiodata::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getFullname())
        {
            binder << getValueOfFullname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMobilePhone())
        {
            binder << getValueOfMobilePhone();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getImage())
        {
            binder << getValueOfImage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getImagePath())
        {
            binder << getValueOfImagePath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCreatedBy())
        {
            binder << getValueOfCreatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreatedOn())
        {
            binder << getValueOfCreatedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getModifiedBy())
        {
            binder << getValueOfModifiedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getModifiedOn())
        {
            binder << getValueOfModifiedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getDeletedBy())
        {
            binder << getValueOfDeletedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getDeletedOn())
        {
            binder << getValueOfDeletedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getIsDelete())
        {
            binder << getValueOfIsDelete();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value MBiodata::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getFullname())
    {
        ret["fullname"]=getValueOfFullname();
    }
    else
    {
        ret["fullname"]=Json::Value();
    }
    if(getMobilePhone())
    {
        ret["mobile_phone"]=getValueOfMobilePhone();
    }
    else
    {
        ret["mobile_phone"]=Json::Value();
    }
    if(getImage())
    {
        ret["image"]=drogon::utils::base64Encode((const unsigned char *)getImage()->data(),getImage()->size());
    }
    else
    {
        ret["image"]=Json::Value();
    }
    if(getImagePath())
    {
        ret["image_path"]=getValueOfImagePath();
    }
    else
    {
        ret["image_path"]=Json::Value();
    }
    if(getCreatedBy())
    {
        ret["created_by"]=(Json::Int64)getValueOfCreatedBy();
    }
    else
    {
        ret["created_by"]=Json::Value();
    }
    if(getCreatedOn())
    {
        ret["created_on"]=getCreatedOn()->toDbStringLocal();
    }
    else
    {
        ret["created_on"]=Json::Value();
    }
    if(getModifiedBy())
    {
        ret["modified_by"]=(Json::Int64)getValueOfModifiedBy();
    }
    else
    {
        ret["modified_by"]=Json::Value();
    }
    if(getModifiedOn())
    {
        ret["modified_on"]=getModifiedOn()->toDbStringLocal();
    }
    else
    {
        ret["modified_on"]=Json::Value();
    }
    if(getDeletedBy())
    {
        ret["deleted_by"]=(Json::Int64)getValueOfDeletedBy();
    }
    else
    {
        ret["deleted_by"]=Json::Value();
    }
    if(getDeletedOn())
    {
        ret["deleted_on"]=getDeletedOn()->toDbStringLocal();
    }
    else
    {
        ret["deleted_on"]=Json::Value();
    }
    if(getIsDelete())
    {
        ret["is_delete"]=getValueOfIsDelete();
    }
    else
    {
        ret["is_delete"]=Json::Value();
    }
    return ret;
}

Json::Value MBiodata::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 12)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getFullname())
            {
                ret[pMasqueradingVector[1]]=getValueOfFullname();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getMobilePhone())
            {
                ret[pMasqueradingVector[2]]=getValueOfMobilePhone();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getImage())
            {
                ret[pMasqueradingVector[3]]=drogon::utils::base64Encode((const unsigned char *)getImage()->data(),getImage()->size());
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getImagePath())
            {
                ret[pMasqueradingVector[4]]=getValueOfImagePath();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getCreatedBy())
            {
                ret[pMasqueradingVector[5]]=(Json::Int64)getValueOfCreatedBy();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getCreatedOn())
            {
                ret[pMasqueradingVector[6]]=getCreatedOn()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getModifiedBy())
            {
                ret[pMasqueradingVector[7]]=(Json::Int64)getValueOfModifiedBy();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getModifiedOn())
            {
                ret[pMasqueradingVector[8]]=getModifiedOn()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getDeletedBy())
            {
                ret[pMasqueradingVector[9]]=(Json::Int64)getValueOfDeletedBy();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getDeletedOn())
            {
                ret[pMasqueradingVector[10]]=getDeletedOn()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getIsDelete())
            {
                ret[pMasqueradingVector[11]]=getValueOfIsDelete();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getFullname())
    {
        ret["fullname"]=getValueOfFullname();
    }
    else
    {
        ret["fullname"]=Json::Value();
    }
    if(getMobilePhone())
    {
        ret["mobile_phone"]=getValueOfMobilePhone();
    }
    else
    {
        ret["mobile_phone"]=Json::Value();
    }
    if(getImage())
    {
        ret["image"]=drogon::utils::base64Encode((const unsigned char *)getImage()->data(),getImage()->size());
    }
    else
    {
        ret["image"]=Json::Value();
    }
    if(getImagePath())
    {
        ret["image_path"]=getValueOfImagePath();
    }
    else
    {
        ret["image_path"]=Json::Value();
    }
    if(getCreatedBy())
    {
        ret["created_by"]=(Json::Int64)getValueOfCreatedBy();
    }
    else
    {
        ret["created_by"]=Json::Value();
    }
    if(getCreatedOn())
    {
        ret["created_on"]=getCreatedOn()->toDbStringLocal();
    }
    else
    {
        ret["created_on"]=Json::Value();
    }
    if(getModifiedBy())
    {
        ret["modified_by"]=(Json::Int64)getValueOfModifiedBy();
    }
    else
    {
        ret["modified_by"]=Json::Value();
    }
    if(getModifiedOn())
    {
        ret["modified_on"]=getModifiedOn()->toDbStringLocal();
    }
    else
    {
        ret["modified_on"]=Json::Value();
    }
    if(getDeletedBy())
    {
        ret["deleted_by"]=(Json::Int64)getValueOfDeletedBy();
    }
    else
    {
        ret["deleted_by"]=Json::Value();
    }
    if(getDeletedOn())
    {
        ret["deleted_on"]=getDeletedOn()->toDbStringLocal();
    }
    else
    {
        ret["deleted_on"]=Json::Value();
    }
    if(getIsDelete())
    {
        ret["is_delete"]=getValueOfIsDelete();
    }
    else
    {
        ret["is_delete"]=Json::Value();
    }
    return ret;
}

bool MBiodata::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("fullname"))
    {
        if(!validJsonOfField(1, "fullname", pJson["fullname"], err, true))
            return false;
    }
    if(pJson.isMember("mobile_phone"))
    {
        if(!validJsonOfField(2, "mobile_phone", pJson["mobile_phone"], err, true))
            return false;
    }
    if(pJson.isMember("image"))
    {
        if(!validJsonOfField(3, "image", pJson["image"], err, true))
            return false;
    }
    if(pJson.isMember("image_path"))
    {
        if(!validJsonOfField(4, "image_path", pJson["image_path"], err, true))
            return false;
    }
    if(pJson.isMember("created_by"))
    {
        if(!validJsonOfField(5, "created_by", pJson["created_by"], err, true))
            return false;
    }
    else
    {
        err="The created_by column cannot be null";
        return false;
    }
    if(pJson.isMember("created_on"))
    {
        if(!validJsonOfField(6, "created_on", pJson["created_on"], err, true))
            return false;
    }
    else
    {
        err="The created_on column cannot be null";
        return false;
    }
    if(pJson.isMember("modified_by"))
    {
        if(!validJsonOfField(7, "modified_by", pJson["modified_by"], err, true))
            return false;
    }
    if(pJson.isMember("modified_on"))
    {
        if(!validJsonOfField(8, "modified_on", pJson["modified_on"], err, true))
            return false;
    }
    if(pJson.isMember("deleted_by"))
    {
        if(!validJsonOfField(9, "deleted_by", pJson["deleted_by"], err, true))
            return false;
    }
    if(pJson.isMember("deleted_on"))
    {
        if(!validJsonOfField(10, "deleted_on", pJson["deleted_on"], err, true))
            return false;
    }
    if(pJson.isMember("is_delete"))
    {
        if(!validJsonOfField(11, "is_delete", pJson["is_delete"], err, true))
            return false;
    }
    return true;
}
bool MBiodata::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 12)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MBiodata::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("fullname"))
    {
        if(!validJsonOfField(1, "fullname", pJson["fullname"], err, false))
            return false;
    }
    if(pJson.isMember("mobile_phone"))
    {
        if(!validJsonOfField(2, "mobile_phone", pJson["mobile_phone"], err, false))
            return false;
    }
    if(pJson.isMember("image"))
    {
        if(!validJsonOfField(3, "image", pJson["image"], err, false))
            return false;
    }
    if(pJson.isMember("image_path"))
    {
        if(!validJsonOfField(4, "image_path", pJson["image_path"], err, false))
            return false;
    }
    if(pJson.isMember("created_by"))
    {
        if(!validJsonOfField(5, "created_by", pJson["created_by"], err, false))
            return false;
    }
    if(pJson.isMember("created_on"))
    {
        if(!validJsonOfField(6, "created_on", pJson["created_on"], err, false))
            return false;
    }
    if(pJson.isMember("modified_by"))
    {
        if(!validJsonOfField(7, "modified_by", pJson["modified_by"], err, false))
            return false;
    }
    if(pJson.isMember("modified_on"))
    {
        if(!validJsonOfField(8, "modified_on", pJson["modified_on"], err, false))
            return false;
    }
    if(pJson.isMember("deleted_by"))
    {
        if(!validJsonOfField(9, "deleted_by", pJson["deleted_by"], err, false))
            return false;
    }
    if(pJson.isMember("deleted_on"))
    {
        if(!validJsonOfField(10, "deleted_on", pJson["deleted_on"], err, false))
            return false;
    }
    if(pJson.isMember("is_delete"))
    {
        if(!validJsonOfField(11, "is_delete", pJson["is_delete"], err, false))
            return false;
    }
    return true;
}
bool MBiodata::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 12)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MBiodata::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 15)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 15)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
