/**
 *
 *  MDoctorEducation.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "MDoctorEducation.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::db_hospital;

const std::string MDoctorEducation::Cols::_id = "id";
const std::string MDoctorEducation::Cols::_doctor_id = "doctor_id";
const std::string MDoctorEducation::Cols::_education_level_id = "education_level_id";
const std::string MDoctorEducation::Cols::_institution_name = "institution_name";
const std::string MDoctorEducation::Cols::_major = "major";
const std::string MDoctorEducation::Cols::_start_year = "start_year";
const std::string MDoctorEducation::Cols::_end_year = "end_year";
const std::string MDoctorEducation::Cols::_is_last_education = "is_last_education";
const std::string MDoctorEducation::Cols::_created_by = "created_by";
const std::string MDoctorEducation::Cols::_created_on = "created_on";
const std::string MDoctorEducation::Cols::_modified_by = "modified_by";
const std::string MDoctorEducation::Cols::_modified_on = "modified_on";
const std::string MDoctorEducation::Cols::_deleted_by = "deleted_by";
const std::string MDoctorEducation::Cols::_deleted_on = "deleted_on";
const std::string MDoctorEducation::Cols::_is_delete = "is_delete";
const std::string MDoctorEducation::primaryKeyName = "id";
const bool MDoctorEducation::hasPrimaryKey = true;
const std::string MDoctorEducation::tableName = "m_doctor_education";

const std::vector<typename MDoctorEducation::MetaData> MDoctorEducation::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"doctor_id","int64_t","bigint",8,0,0,0},
{"education_level_id","int64_t","bigint",8,0,0,0},
{"institution_name","std::string","character varying",100,0,0,0},
{"major","std::string","character varying",100,0,0,0},
{"start_year","std::string","character varying",4,0,0,0},
{"end_year","std::string","character varying",4,0,0,0},
{"is_last_education","bool","boolean",1,0,0,0},
{"created_by","int64_t","bigint",8,0,0,1},
{"created_on","::trantor::Date","timestamp without time zone",0,0,0,1},
{"modified_by","int64_t","bigint",8,0,0,0},
{"modified_on","::trantor::Date","timestamp without time zone",0,0,0,0},
{"deleted_by","int64_t","bigint",8,0,0,0},
{"deleted_on","::trantor::Date","timestamp without time zone",0,0,0,0},
{"is_delete","bool","boolean",1,0,0,1}
};
const std::string &MDoctorEducation::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
MDoctorEducation::MDoctorEducation(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["doctor_id"].isNull())
        {
            doctorId_=std::make_shared<int64_t>(r["doctor_id"].as<int64_t>());
        }
        if(!r["education_level_id"].isNull())
        {
            educationLevelId_=std::make_shared<int64_t>(r["education_level_id"].as<int64_t>());
        }
        if(!r["institution_name"].isNull())
        {
            institutionName_=std::make_shared<std::string>(r["institution_name"].as<std::string>());
        }
        if(!r["major"].isNull())
        {
            major_=std::make_shared<std::string>(r["major"].as<std::string>());
        }
        if(!r["start_year"].isNull())
        {
            startYear_=std::make_shared<std::string>(r["start_year"].as<std::string>());
        }
        if(!r["end_year"].isNull())
        {
            endYear_=std::make_shared<std::string>(r["end_year"].as<std::string>());
        }
        if(!r["is_last_education"].isNull())
        {
            isLastEducation_=std::make_shared<bool>(r["is_last_education"].as<bool>());
        }
        if(!r["created_by"].isNull())
        {
            createdBy_=std::make_shared<int64_t>(r["created_by"].as<int64_t>());
        }
        if(!r["created_on"].isNull())
        {
            auto timeStr = r["created_on"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["modified_by"].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>(r["modified_by"].as<int64_t>());
        }
        if(!r["modified_on"].isNull())
        {
            auto timeStr = r["modified_on"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["deleted_by"].isNull())
        {
            deletedBy_=std::make_shared<int64_t>(r["deleted_by"].as<int64_t>());
        }
        if(!r["deleted_on"].isNull())
        {
            auto timeStr = r["deleted_on"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["is_delete"].isNull())
        {
            isDelete_=std::make_shared<bool>(r["is_delete"].as<bool>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 15 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            doctorId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            educationLevelId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            institutionName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            major_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            startYear_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            endYear_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            isLastEducation_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            createdBy_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            deletedBy_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 14;
        if(!r[index].isNull())
        {
            isDelete_=std::make_shared<bool>(r[index].as<bool>());
        }
    }

}

MDoctorEducation::MDoctorEducation(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 15)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            doctorId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            educationLevelId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            institutionName_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            major_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            startYear_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            endYear_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            isLastEducation_=std::make_shared<bool>(pJson[pMasqueradingVector[7]].asBool());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[12]].asInt64());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[13]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson[pMasqueradingVector[14]].asBool());
        }
    }
}

MDoctorEducation::MDoctorEducation(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("doctor_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["doctor_id"].isNull())
        {
            doctorId_=std::make_shared<int64_t>((int64_t)pJson["doctor_id"].asInt64());
        }
    }
    if(pJson.isMember("education_level_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["education_level_id"].isNull())
        {
            educationLevelId_=std::make_shared<int64_t>((int64_t)pJson["education_level_id"].asInt64());
        }
    }
    if(pJson.isMember("institution_name"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["institution_name"].isNull())
        {
            institutionName_=std::make_shared<std::string>(pJson["institution_name"].asString());
        }
    }
    if(pJson.isMember("major"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["major"].isNull())
        {
            major_=std::make_shared<std::string>(pJson["major"].asString());
        }
    }
    if(pJson.isMember("start_year"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["start_year"].isNull())
        {
            startYear_=std::make_shared<std::string>(pJson["start_year"].asString());
        }
    }
    if(pJson.isMember("end_year"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["end_year"].isNull())
        {
            endYear_=std::make_shared<std::string>(pJson["end_year"].asString());
        }
    }
    if(pJson.isMember("is_last_education"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["is_last_education"].isNull())
        {
            isLastEducation_=std::make_shared<bool>(pJson["is_last_education"].asBool());
        }
    }
    if(pJson.isMember("created_by"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["created_by"].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson["created_by"].asInt64());
        }
    }
    if(pJson.isMember("created_on"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["created_on"].isNull())
        {
            auto timeStr = pJson["created_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("modified_by"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["modified_by"].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson["modified_by"].asInt64());
        }
    }
    if(pJson.isMember("modified_on"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["modified_on"].isNull())
        {
            auto timeStr = pJson["modified_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("deleted_by"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["deleted_by"].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson["deleted_by"].asInt64());
        }
    }
    if(pJson.isMember("deleted_on"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["deleted_on"].isNull())
        {
            auto timeStr = pJson["deleted_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("is_delete"))
    {
        dirtyFlag_[14]=true;
        if(!pJson["is_delete"].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson["is_delete"].asBool());
        }
    }
}

void MDoctorEducation::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 15)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            doctorId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            educationLevelId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            institutionName_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            major_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            startYear_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            endYear_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            isLastEducation_=std::make_shared<bool>(pJson[pMasqueradingVector[7]].asBool());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[12]].asInt64());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[13]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson[pMasqueradingVector[14]].asBool());
        }
    }
}

void MDoctorEducation::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("doctor_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["doctor_id"].isNull())
        {
            doctorId_=std::make_shared<int64_t>((int64_t)pJson["doctor_id"].asInt64());
        }
    }
    if(pJson.isMember("education_level_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["education_level_id"].isNull())
        {
            educationLevelId_=std::make_shared<int64_t>((int64_t)pJson["education_level_id"].asInt64());
        }
    }
    if(pJson.isMember("institution_name"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["institution_name"].isNull())
        {
            institutionName_=std::make_shared<std::string>(pJson["institution_name"].asString());
        }
    }
    if(pJson.isMember("major"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["major"].isNull())
        {
            major_=std::make_shared<std::string>(pJson["major"].asString());
        }
    }
    if(pJson.isMember("start_year"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["start_year"].isNull())
        {
            startYear_=std::make_shared<std::string>(pJson["start_year"].asString());
        }
    }
    if(pJson.isMember("end_year"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["end_year"].isNull())
        {
            endYear_=std::make_shared<std::string>(pJson["end_year"].asString());
        }
    }
    if(pJson.isMember("is_last_education"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["is_last_education"].isNull())
        {
            isLastEducation_=std::make_shared<bool>(pJson["is_last_education"].asBool());
        }
    }
    if(pJson.isMember("created_by"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["created_by"].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson["created_by"].asInt64());
        }
    }
    if(pJson.isMember("created_on"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["created_on"].isNull())
        {
            auto timeStr = pJson["created_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("modified_by"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["modified_by"].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson["modified_by"].asInt64());
        }
    }
    if(pJson.isMember("modified_on"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["modified_on"].isNull())
        {
            auto timeStr = pJson["modified_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("deleted_by"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["deleted_by"].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson["deleted_by"].asInt64());
        }
    }
    if(pJson.isMember("deleted_on"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["deleted_on"].isNull())
        {
            auto timeStr = pJson["deleted_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("is_delete"))
    {
        dirtyFlag_[14] = true;
        if(!pJson["is_delete"].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson["is_delete"].asBool());
        }
    }
}

const int64_t &MDoctorEducation::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MDoctorEducation::getId() const noexcept
{
    return id_;
}
void MDoctorEducation::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename MDoctorEducation::PrimaryKeyType & MDoctorEducation::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &MDoctorEducation::getValueOfDoctorId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(doctorId_)
        return *doctorId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MDoctorEducation::getDoctorId() const noexcept
{
    return doctorId_;
}
void MDoctorEducation::setDoctorId(const int64_t &pDoctorId) noexcept
{
    doctorId_ = std::make_shared<int64_t>(pDoctorId);
    dirtyFlag_[1] = true;
}
void MDoctorEducation::setDoctorIdToNull() noexcept
{
    doctorId_.reset();
    dirtyFlag_[1] = true;
}

const int64_t &MDoctorEducation::getValueOfEducationLevelId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(educationLevelId_)
        return *educationLevelId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MDoctorEducation::getEducationLevelId() const noexcept
{
    return educationLevelId_;
}
void MDoctorEducation::setEducationLevelId(const int64_t &pEducationLevelId) noexcept
{
    educationLevelId_ = std::make_shared<int64_t>(pEducationLevelId);
    dirtyFlag_[2] = true;
}
void MDoctorEducation::setEducationLevelIdToNull() noexcept
{
    educationLevelId_.reset();
    dirtyFlag_[2] = true;
}

const std::string &MDoctorEducation::getValueOfInstitutionName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(institutionName_)
        return *institutionName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MDoctorEducation::getInstitutionName() const noexcept
{
    return institutionName_;
}
void MDoctorEducation::setInstitutionName(const std::string &pInstitutionName) noexcept
{
    institutionName_ = std::make_shared<std::string>(pInstitutionName);
    dirtyFlag_[3] = true;
}
void MDoctorEducation::setInstitutionName(std::string &&pInstitutionName) noexcept
{
    institutionName_ = std::make_shared<std::string>(std::move(pInstitutionName));
    dirtyFlag_[3] = true;
}
void MDoctorEducation::setInstitutionNameToNull() noexcept
{
    institutionName_.reset();
    dirtyFlag_[3] = true;
}

const std::string &MDoctorEducation::getValueOfMajor() const noexcept
{
    static const std::string defaultValue = std::string();
    if(major_)
        return *major_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MDoctorEducation::getMajor() const noexcept
{
    return major_;
}
void MDoctorEducation::setMajor(const std::string &pMajor) noexcept
{
    major_ = std::make_shared<std::string>(pMajor);
    dirtyFlag_[4] = true;
}
void MDoctorEducation::setMajor(std::string &&pMajor) noexcept
{
    major_ = std::make_shared<std::string>(std::move(pMajor));
    dirtyFlag_[4] = true;
}
void MDoctorEducation::setMajorToNull() noexcept
{
    major_.reset();
    dirtyFlag_[4] = true;
}

const std::string &MDoctorEducation::getValueOfStartYear() const noexcept
{
    static const std::string defaultValue = std::string();
    if(startYear_)
        return *startYear_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MDoctorEducation::getStartYear() const noexcept
{
    return startYear_;
}
void MDoctorEducation::setStartYear(const std::string &pStartYear) noexcept
{
    startYear_ = std::make_shared<std::string>(pStartYear);
    dirtyFlag_[5] = true;
}
void MDoctorEducation::setStartYear(std::string &&pStartYear) noexcept
{
    startYear_ = std::make_shared<std::string>(std::move(pStartYear));
    dirtyFlag_[5] = true;
}
void MDoctorEducation::setStartYearToNull() noexcept
{
    startYear_.reset();
    dirtyFlag_[5] = true;
}

const std::string &MDoctorEducation::getValueOfEndYear() const noexcept
{
    static const std::string defaultValue = std::string();
    if(endYear_)
        return *endYear_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MDoctorEducation::getEndYear() const noexcept
{
    return endYear_;
}
void MDoctorEducation::setEndYear(const std::string &pEndYear) noexcept
{
    endYear_ = std::make_shared<std::string>(pEndYear);
    dirtyFlag_[6] = true;
}
void MDoctorEducation::setEndYear(std::string &&pEndYear) noexcept
{
    endYear_ = std::make_shared<std::string>(std::move(pEndYear));
    dirtyFlag_[6] = true;
}
void MDoctorEducation::setEndYearToNull() noexcept
{
    endYear_.reset();
    dirtyFlag_[6] = true;
}

const bool &MDoctorEducation::getValueOfIsLastEducation() const noexcept
{
    static const bool defaultValue = bool();
    if(isLastEducation_)
        return *isLastEducation_;
    return defaultValue;
}
const std::shared_ptr<bool> &MDoctorEducation::getIsLastEducation() const noexcept
{
    return isLastEducation_;
}
void MDoctorEducation::setIsLastEducation(const bool &pIsLastEducation) noexcept
{
    isLastEducation_ = std::make_shared<bool>(pIsLastEducation);
    dirtyFlag_[7] = true;
}
void MDoctorEducation::setIsLastEducationToNull() noexcept
{
    isLastEducation_.reset();
    dirtyFlag_[7] = true;
}

const int64_t &MDoctorEducation::getValueOfCreatedBy() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(createdBy_)
        return *createdBy_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MDoctorEducation::getCreatedBy() const noexcept
{
    return createdBy_;
}
void MDoctorEducation::setCreatedBy(const int64_t &pCreatedBy) noexcept
{
    createdBy_ = std::make_shared<int64_t>(pCreatedBy);
    dirtyFlag_[8] = true;
}

const ::trantor::Date &MDoctorEducation::getValueOfCreatedOn() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdOn_)
        return *createdOn_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &MDoctorEducation::getCreatedOn() const noexcept
{
    return createdOn_;
}
void MDoctorEducation::setCreatedOn(const ::trantor::Date &pCreatedOn) noexcept
{
    createdOn_ = std::make_shared<::trantor::Date>(pCreatedOn);
    dirtyFlag_[9] = true;
}

const int64_t &MDoctorEducation::getValueOfModifiedBy() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(modifiedBy_)
        return *modifiedBy_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MDoctorEducation::getModifiedBy() const noexcept
{
    return modifiedBy_;
}
void MDoctorEducation::setModifiedBy(const int64_t &pModifiedBy) noexcept
{
    modifiedBy_ = std::make_shared<int64_t>(pModifiedBy);
    dirtyFlag_[10] = true;
}
void MDoctorEducation::setModifiedByToNull() noexcept
{
    modifiedBy_.reset();
    dirtyFlag_[10] = true;
}

const ::trantor::Date &MDoctorEducation::getValueOfModifiedOn() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(modifiedOn_)
        return *modifiedOn_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &MDoctorEducation::getModifiedOn() const noexcept
{
    return modifiedOn_;
}
void MDoctorEducation::setModifiedOn(const ::trantor::Date &pModifiedOn) noexcept
{
    modifiedOn_ = std::make_shared<::trantor::Date>(pModifiedOn);
    dirtyFlag_[11] = true;
}
void MDoctorEducation::setModifiedOnToNull() noexcept
{
    modifiedOn_.reset();
    dirtyFlag_[11] = true;
}

const int64_t &MDoctorEducation::getValueOfDeletedBy() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(deletedBy_)
        return *deletedBy_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &MDoctorEducation::getDeletedBy() const noexcept
{
    return deletedBy_;
}
void MDoctorEducation::setDeletedBy(const int64_t &pDeletedBy) noexcept
{
    deletedBy_ = std::make_shared<int64_t>(pDeletedBy);
    dirtyFlag_[12] = true;
}
void MDoctorEducation::setDeletedByToNull() noexcept
{
    deletedBy_.reset();
    dirtyFlag_[12] = true;
}

const ::trantor::Date &MDoctorEducation::getValueOfDeletedOn() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(deletedOn_)
        return *deletedOn_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &MDoctorEducation::getDeletedOn() const noexcept
{
    return deletedOn_;
}
void MDoctorEducation::setDeletedOn(const ::trantor::Date &pDeletedOn) noexcept
{
    deletedOn_ = std::make_shared<::trantor::Date>(pDeletedOn);
    dirtyFlag_[13] = true;
}
void MDoctorEducation::setDeletedOnToNull() noexcept
{
    deletedOn_.reset();
    dirtyFlag_[13] = true;
}

const bool &MDoctorEducation::getValueOfIsDelete() const noexcept
{
    static const bool defaultValue = bool();
    if(isDelete_)
        return *isDelete_;
    return defaultValue;
}
const std::shared_ptr<bool> &MDoctorEducation::getIsDelete() const noexcept
{
    return isDelete_;
}
void MDoctorEducation::setIsDelete(const bool &pIsDelete) noexcept
{
    isDelete_ = std::make_shared<bool>(pIsDelete);
    dirtyFlag_[14] = true;
}

void MDoctorEducation::updateId(const uint64_t id)
{
}

const std::vector<std::string> &MDoctorEducation::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "doctor_id",
        "education_level_id",
        "institution_name",
        "major",
        "start_year",
        "end_year",
        "is_last_education",
        "created_by",
        "created_on",
        "modified_by",
        "modified_on",
        "deleted_by",
        "deleted_on",
        "is_delete"
    };
    return inCols;
}

void MDoctorEducation::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getDoctorId())
        {
            binder << getValueOfDoctorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getEducationLevelId())
        {
            binder << getValueOfEducationLevelId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getInstitutionName())
        {
            binder << getValueOfInstitutionName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getMajor())
        {
            binder << getValueOfMajor();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getStartYear())
        {
            binder << getValueOfStartYear();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getEndYear())
        {
            binder << getValueOfEndYear();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getIsLastEducation())
        {
            binder << getValueOfIsLastEducation();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getCreatedBy())
        {
            binder << getValueOfCreatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCreatedOn())
        {
            binder << getValueOfCreatedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getModifiedBy())
        {
            binder << getValueOfModifiedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getModifiedOn())
        {
            binder << getValueOfModifiedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getDeletedBy())
        {
            binder << getValueOfDeletedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getDeletedOn())
        {
            binder << getValueOfDeletedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getIsDelete())
        {
            binder << getValueOfIsDelete();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> MDoctorEducation::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    if(dirtyFlag_[14])
    {
        ret.push_back(getColumnName(14));
    }
    return ret;
}

void MDoctorEducation::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getDoctorId())
        {
            binder << getValueOfDoctorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getEducationLevelId())
        {
            binder << getValueOfEducationLevelId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getInstitutionName())
        {
            binder << getValueOfInstitutionName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getMajor())
        {
            binder << getValueOfMajor();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getStartYear())
        {
            binder << getValueOfStartYear();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getEndYear())
        {
            binder << getValueOfEndYear();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getIsLastEducation())
        {
            binder << getValueOfIsLastEducation();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getCreatedBy())
        {
            binder << getValueOfCreatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCreatedOn())
        {
            binder << getValueOfCreatedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getModifiedBy())
        {
            binder << getValueOfModifiedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getModifiedOn())
        {
            binder << getValueOfModifiedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getDeletedBy())
        {
            binder << getValueOfDeletedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getDeletedOn())
        {
            binder << getValueOfDeletedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getIsDelete())
        {
            binder << getValueOfIsDelete();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value MDoctorEducation::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getDoctorId())
    {
        ret["doctor_id"]=(Json::Int64)getValueOfDoctorId();
    }
    else
    {
        ret["doctor_id"]=Json::Value();
    }
    if(getEducationLevelId())
    {
        ret["education_level_id"]=(Json::Int64)getValueOfEducationLevelId();
    }
    else
    {
        ret["education_level_id"]=Json::Value();
    }
    if(getInstitutionName())
    {
        ret["institution_name"]=getValueOfInstitutionName();
    }
    else
    {
        ret["institution_name"]=Json::Value();
    }
    if(getMajor())
    {
        ret["major"]=getValueOfMajor();
    }
    else
    {
        ret["major"]=Json::Value();
    }
    if(getStartYear())
    {
        ret["start_year"]=getValueOfStartYear();
    }
    else
    {
        ret["start_year"]=Json::Value();
    }
    if(getEndYear())
    {
        ret["end_year"]=getValueOfEndYear();
    }
    else
    {
        ret["end_year"]=Json::Value();
    }
    if(getIsLastEducation())
    {
        ret["is_last_education"]=getValueOfIsLastEducation();
    }
    else
    {
        ret["is_last_education"]=Json::Value();
    }
    if(getCreatedBy())
    {
        ret["created_by"]=(Json::Int64)getValueOfCreatedBy();
    }
    else
    {
        ret["created_by"]=Json::Value();
    }
    if(getCreatedOn())
    {
        ret["created_on"]=getCreatedOn()->toDbStringLocal();
    }
    else
    {
        ret["created_on"]=Json::Value();
    }
    if(getModifiedBy())
    {
        ret["modified_by"]=(Json::Int64)getValueOfModifiedBy();
    }
    else
    {
        ret["modified_by"]=Json::Value();
    }
    if(getModifiedOn())
    {
        ret["modified_on"]=getModifiedOn()->toDbStringLocal();
    }
    else
    {
        ret["modified_on"]=Json::Value();
    }
    if(getDeletedBy())
    {
        ret["deleted_by"]=(Json::Int64)getValueOfDeletedBy();
    }
    else
    {
        ret["deleted_by"]=Json::Value();
    }
    if(getDeletedOn())
    {
        ret["deleted_on"]=getDeletedOn()->toDbStringLocal();
    }
    else
    {
        ret["deleted_on"]=Json::Value();
    }
    if(getIsDelete())
    {
        ret["is_delete"]=getValueOfIsDelete();
    }
    else
    {
        ret["is_delete"]=Json::Value();
    }
    return ret;
}

Json::Value MDoctorEducation::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 15)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getDoctorId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfDoctorId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getEducationLevelId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfEducationLevelId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getInstitutionName())
            {
                ret[pMasqueradingVector[3]]=getValueOfInstitutionName();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getMajor())
            {
                ret[pMasqueradingVector[4]]=getValueOfMajor();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getStartYear())
            {
                ret[pMasqueradingVector[5]]=getValueOfStartYear();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getEndYear())
            {
                ret[pMasqueradingVector[6]]=getValueOfEndYear();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getIsLastEducation())
            {
                ret[pMasqueradingVector[7]]=getValueOfIsLastEducation();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getCreatedBy())
            {
                ret[pMasqueradingVector[8]]=(Json::Int64)getValueOfCreatedBy();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getCreatedOn())
            {
                ret[pMasqueradingVector[9]]=getCreatedOn()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getModifiedBy())
            {
                ret[pMasqueradingVector[10]]=(Json::Int64)getValueOfModifiedBy();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getModifiedOn())
            {
                ret[pMasqueradingVector[11]]=getModifiedOn()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getDeletedBy())
            {
                ret[pMasqueradingVector[12]]=(Json::Int64)getValueOfDeletedBy();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getDeletedOn())
            {
                ret[pMasqueradingVector[13]]=getDeletedOn()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[14].empty())
        {
            if(getIsDelete())
            {
                ret[pMasqueradingVector[14]]=getValueOfIsDelete();
            }
            else
            {
                ret[pMasqueradingVector[14]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getDoctorId())
    {
        ret["doctor_id"]=(Json::Int64)getValueOfDoctorId();
    }
    else
    {
        ret["doctor_id"]=Json::Value();
    }
    if(getEducationLevelId())
    {
        ret["education_level_id"]=(Json::Int64)getValueOfEducationLevelId();
    }
    else
    {
        ret["education_level_id"]=Json::Value();
    }
    if(getInstitutionName())
    {
        ret["institution_name"]=getValueOfInstitutionName();
    }
    else
    {
        ret["institution_name"]=Json::Value();
    }
    if(getMajor())
    {
        ret["major"]=getValueOfMajor();
    }
    else
    {
        ret["major"]=Json::Value();
    }
    if(getStartYear())
    {
        ret["start_year"]=getValueOfStartYear();
    }
    else
    {
        ret["start_year"]=Json::Value();
    }
    if(getEndYear())
    {
        ret["end_year"]=getValueOfEndYear();
    }
    else
    {
        ret["end_year"]=Json::Value();
    }
    if(getIsLastEducation())
    {
        ret["is_last_education"]=getValueOfIsLastEducation();
    }
    else
    {
        ret["is_last_education"]=Json::Value();
    }
    if(getCreatedBy())
    {
        ret["created_by"]=(Json::Int64)getValueOfCreatedBy();
    }
    else
    {
        ret["created_by"]=Json::Value();
    }
    if(getCreatedOn())
    {
        ret["created_on"]=getCreatedOn()->toDbStringLocal();
    }
    else
    {
        ret["created_on"]=Json::Value();
    }
    if(getModifiedBy())
    {
        ret["modified_by"]=(Json::Int64)getValueOfModifiedBy();
    }
    else
    {
        ret["modified_by"]=Json::Value();
    }
    if(getModifiedOn())
    {
        ret["modified_on"]=getModifiedOn()->toDbStringLocal();
    }
    else
    {
        ret["modified_on"]=Json::Value();
    }
    if(getDeletedBy())
    {
        ret["deleted_by"]=(Json::Int64)getValueOfDeletedBy();
    }
    else
    {
        ret["deleted_by"]=Json::Value();
    }
    if(getDeletedOn())
    {
        ret["deleted_on"]=getDeletedOn()->toDbStringLocal();
    }
    else
    {
        ret["deleted_on"]=Json::Value();
    }
    if(getIsDelete())
    {
        ret["is_delete"]=getValueOfIsDelete();
    }
    else
    {
        ret["is_delete"]=Json::Value();
    }
    return ret;
}

bool MDoctorEducation::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("doctor_id"))
    {
        if(!validJsonOfField(1, "doctor_id", pJson["doctor_id"], err, true))
            return false;
    }
    if(pJson.isMember("education_level_id"))
    {
        if(!validJsonOfField(2, "education_level_id", pJson["education_level_id"], err, true))
            return false;
    }
    if(pJson.isMember("institution_name"))
    {
        if(!validJsonOfField(3, "institution_name", pJson["institution_name"], err, true))
            return false;
    }
    if(pJson.isMember("major"))
    {
        if(!validJsonOfField(4, "major", pJson["major"], err, true))
            return false;
    }
    if(pJson.isMember("start_year"))
    {
        if(!validJsonOfField(5, "start_year", pJson["start_year"], err, true))
            return false;
    }
    if(pJson.isMember("end_year"))
    {
        if(!validJsonOfField(6, "end_year", pJson["end_year"], err, true))
            return false;
    }
    if(pJson.isMember("is_last_education"))
    {
        if(!validJsonOfField(7, "is_last_education", pJson["is_last_education"], err, true))
            return false;
    }
    if(pJson.isMember("created_by"))
    {
        if(!validJsonOfField(8, "created_by", pJson["created_by"], err, true))
            return false;
    }
    else
    {
        err="The created_by column cannot be null";
        return false;
    }
    if(pJson.isMember("created_on"))
    {
        if(!validJsonOfField(9, "created_on", pJson["created_on"], err, true))
            return false;
    }
    else
    {
        err="The created_on column cannot be null";
        return false;
    }
    if(pJson.isMember("modified_by"))
    {
        if(!validJsonOfField(10, "modified_by", pJson["modified_by"], err, true))
            return false;
    }
    if(pJson.isMember("modified_on"))
    {
        if(!validJsonOfField(11, "modified_on", pJson["modified_on"], err, true))
            return false;
    }
    if(pJson.isMember("deleted_by"))
    {
        if(!validJsonOfField(12, "deleted_by", pJson["deleted_by"], err, true))
            return false;
    }
    if(pJson.isMember("deleted_on"))
    {
        if(!validJsonOfField(13, "deleted_on", pJson["deleted_on"], err, true))
            return false;
    }
    if(pJson.isMember("is_delete"))
    {
        if(!validJsonOfField(14, "is_delete", pJson["is_delete"], err, true))
            return false;
    }
    return true;
}
bool MDoctorEducation::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                          const std::vector<std::string> &pMasqueradingVector,
                                                          std::string &err)
{
    if(pMasqueradingVector.size() != 15)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[8] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[9] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[14].empty())
      {
          if(pJson.isMember(pMasqueradingVector[14]))
          {
              if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MDoctorEducation::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("doctor_id"))
    {
        if(!validJsonOfField(1, "doctor_id", pJson["doctor_id"], err, false))
            return false;
    }
    if(pJson.isMember("education_level_id"))
    {
        if(!validJsonOfField(2, "education_level_id", pJson["education_level_id"], err, false))
            return false;
    }
    if(pJson.isMember("institution_name"))
    {
        if(!validJsonOfField(3, "institution_name", pJson["institution_name"], err, false))
            return false;
    }
    if(pJson.isMember("major"))
    {
        if(!validJsonOfField(4, "major", pJson["major"], err, false))
            return false;
    }
    if(pJson.isMember("start_year"))
    {
        if(!validJsonOfField(5, "start_year", pJson["start_year"], err, false))
            return false;
    }
    if(pJson.isMember("end_year"))
    {
        if(!validJsonOfField(6, "end_year", pJson["end_year"], err, false))
            return false;
    }
    if(pJson.isMember("is_last_education"))
    {
        if(!validJsonOfField(7, "is_last_education", pJson["is_last_education"], err, false))
            return false;
    }
    if(pJson.isMember("created_by"))
    {
        if(!validJsonOfField(8, "created_by", pJson["created_by"], err, false))
            return false;
    }
    if(pJson.isMember("created_on"))
    {
        if(!validJsonOfField(9, "created_on", pJson["created_on"], err, false))
            return false;
    }
    if(pJson.isMember("modified_by"))
    {
        if(!validJsonOfField(10, "modified_by", pJson["modified_by"], err, false))
            return false;
    }
    if(pJson.isMember("modified_on"))
    {
        if(!validJsonOfField(11, "modified_on", pJson["modified_on"], err, false))
            return false;
    }
    if(pJson.isMember("deleted_by"))
    {
        if(!validJsonOfField(12, "deleted_by", pJson["deleted_by"], err, false))
            return false;
    }
    if(pJson.isMember("deleted_on"))
    {
        if(!validJsonOfField(13, "deleted_on", pJson["deleted_on"], err, false))
            return false;
    }
    if(pJson.isMember("is_delete"))
    {
        if(!validJsonOfField(14, "is_delete", pJson["is_delete"], err, false))
            return false;
    }
    return true;
}
bool MDoctorEducation::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 15)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
      if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
      {
          if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MDoctorEducation::validJsonOfField(size_t index,
                                        const std::string &fieldName,
                                        const Json::Value &pJson,
                                        std::string &err,
                                        bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }

            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }

            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 4)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 4)";
                return false;
            }

            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 4)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 4)";
                return false;
            }

            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 14:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
