/**
 *
 *  TMedicalItemPurchaseDetail.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "TMedicalItemPurchaseDetail.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::db_hospital;

const std::string TMedicalItemPurchaseDetail::Cols::_id = "id";
const std::string TMedicalItemPurchaseDetail::Cols::_medical_item_purchase_id = "medical_item_purchase_id";
const std::string TMedicalItemPurchaseDetail::Cols::_medical_item_id = "medical_item_id";
const std::string TMedicalItemPurchaseDetail::Cols::_qty = "qty";
const std::string TMedicalItemPurchaseDetail::Cols::_medical_facility_id = "medical_facility_id";
const std::string TMedicalItemPurchaseDetail::Cols::_courir_id = "courir_id";
const std::string TMedicalItemPurchaseDetail::Cols::_sub_total = "sub_total";
const std::string TMedicalItemPurchaseDetail::Cols::_created_by = "created_by";
const std::string TMedicalItemPurchaseDetail::Cols::_created_on = "created_on";
const std::string TMedicalItemPurchaseDetail::Cols::_modified_by = "modified_by";
const std::string TMedicalItemPurchaseDetail::Cols::_modified_on = "modified_on";
const std::string TMedicalItemPurchaseDetail::Cols::_deleted_by = "deleted_by";
const std::string TMedicalItemPurchaseDetail::Cols::_deleted_on = "deleted_on";
const std::string TMedicalItemPurchaseDetail::Cols::_is_delete = "is_delete";
const std::string TMedicalItemPurchaseDetail::primaryKeyName = "id";
const bool TMedicalItemPurchaseDetail::hasPrimaryKey = true;
const std::string TMedicalItemPurchaseDetail::tableName = "t_medical_item_purchase_detail";

const std::vector<typename TMedicalItemPurchaseDetail::MetaData> TMedicalItemPurchaseDetail::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"medical_item_purchase_id","int64_t","bigint",8,0,0,0},
{"medical_item_id","int64_t","bigint",8,0,0,0},
{"qty","int32_t","integer",4,0,0,0},
{"medical_facility_id","int64_t","bigint",8,0,0,0},
{"courir_id","int64_t","bigint",8,0,0,0},
{"sub_total","std::string","numeric",0,0,0,0},
{"created_by","int64_t","bigint",8,0,0,1},
{"created_on","::trantor::Date","timestamp without time zone",0,0,0,1},
{"modified_by","int64_t","bigint",8,0,0,0},
{"modified_on","::trantor::Date","timestamp without time zone",0,0,0,0},
{"deleted_by","int64_t","bigint",8,0,0,0},
{"deleted_on","::trantor::Date","timestamp without time zone",0,0,0,0},
{"is_delete","bool","boolean",1,0,0,1}
};
const std::string &TMedicalItemPurchaseDetail::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
TMedicalItemPurchaseDetail::TMedicalItemPurchaseDetail(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["medical_item_purchase_id"].isNull())
        {
            medicalItemPurchaseId_=std::make_shared<int64_t>(r["medical_item_purchase_id"].as<int64_t>());
        }
        if(!r["medical_item_id"].isNull())
        {
            medicalItemId_=std::make_shared<int64_t>(r["medical_item_id"].as<int64_t>());
        }
        if(!r["qty"].isNull())
        {
            qty_=std::make_shared<int32_t>(r["qty"].as<int32_t>());
        }
        if(!r["medical_facility_id"].isNull())
        {
            medicalFacilityId_=std::make_shared<int64_t>(r["medical_facility_id"].as<int64_t>());
        }
        if(!r["courir_id"].isNull())
        {
            courirId_=std::make_shared<int64_t>(r["courir_id"].as<int64_t>());
        }
        if(!r["sub_total"].isNull())
        {
            subTotal_=std::make_shared<std::string>(r["sub_total"].as<std::string>());
        }
        if(!r["created_by"].isNull())
        {
            createdBy_=std::make_shared<int64_t>(r["created_by"].as<int64_t>());
        }
        if(!r["created_on"].isNull())
        {
            auto timeStr = r["created_on"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["modified_by"].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>(r["modified_by"].as<int64_t>());
        }
        if(!r["modified_on"].isNull())
        {
            auto timeStr = r["modified_on"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["deleted_by"].isNull())
        {
            deletedBy_=std::make_shared<int64_t>(r["deleted_by"].as<int64_t>());
        }
        if(!r["deleted_on"].isNull())
        {
            auto timeStr = r["deleted_on"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["is_delete"].isNull())
        {
            isDelete_=std::make_shared<bool>(r["is_delete"].as<bool>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 14 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            medicalItemPurchaseId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            medicalItemId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            qty_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            medicalFacilityId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            courirId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            subTotal_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            createdBy_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            deletedBy_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            isDelete_=std::make_shared<bool>(r[index].as<bool>());
        }
    }

}

TMedicalItemPurchaseDetail::TMedicalItemPurchaseDetail(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            medicalItemPurchaseId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            medicalItemId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            qty_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            medicalFacilityId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            courirId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            subTotal_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[11]].asInt64());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson[pMasqueradingVector[13]].asBool());
        }
    }
}

TMedicalItemPurchaseDetail::TMedicalItemPurchaseDetail(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("medical_item_purchase_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["medical_item_purchase_id"].isNull())
        {
            medicalItemPurchaseId_=std::make_shared<int64_t>((int64_t)pJson["medical_item_purchase_id"].asInt64());
        }
    }
    if(pJson.isMember("medical_item_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["medical_item_id"].isNull())
        {
            medicalItemId_=std::make_shared<int64_t>((int64_t)pJson["medical_item_id"].asInt64());
        }
    }
    if(pJson.isMember("qty"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["qty"].isNull())
        {
            qty_=std::make_shared<int32_t>((int32_t)pJson["qty"].asInt64());
        }
    }
    if(pJson.isMember("medical_facility_id"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["medical_facility_id"].isNull())
        {
            medicalFacilityId_=std::make_shared<int64_t>((int64_t)pJson["medical_facility_id"].asInt64());
        }
    }
    if(pJson.isMember("courir_id"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["courir_id"].isNull())
        {
            courirId_=std::make_shared<int64_t>((int64_t)pJson["courir_id"].asInt64());
        }
    }
    if(pJson.isMember("sub_total"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["sub_total"].isNull())
        {
            subTotal_=std::make_shared<std::string>(pJson["sub_total"].asString());
        }
    }
    if(pJson.isMember("created_by"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["created_by"].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson["created_by"].asInt64());
        }
    }
    if(pJson.isMember("created_on"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["created_on"].isNull())
        {
            auto timeStr = pJson["created_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("modified_by"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["modified_by"].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson["modified_by"].asInt64());
        }
    }
    if(pJson.isMember("modified_on"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["modified_on"].isNull())
        {
            auto timeStr = pJson["modified_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("deleted_by"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["deleted_by"].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson["deleted_by"].asInt64());
        }
    }
    if(pJson.isMember("deleted_on"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["deleted_on"].isNull())
        {
            auto timeStr = pJson["deleted_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("is_delete"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["is_delete"].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson["is_delete"].asBool());
        }
    }
}

void TMedicalItemPurchaseDetail::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            medicalItemPurchaseId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            medicalItemId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            qty_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            medicalFacilityId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            courirId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            subTotal_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[11]].asInt64());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson[pMasqueradingVector[13]].asBool());
        }
    }
}

void TMedicalItemPurchaseDetail::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("medical_item_purchase_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["medical_item_purchase_id"].isNull())
        {
            medicalItemPurchaseId_=std::make_shared<int64_t>((int64_t)pJson["medical_item_purchase_id"].asInt64());
        }
    }
    if(pJson.isMember("medical_item_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["medical_item_id"].isNull())
        {
            medicalItemId_=std::make_shared<int64_t>((int64_t)pJson["medical_item_id"].asInt64());
        }
    }
    if(pJson.isMember("qty"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["qty"].isNull())
        {
            qty_=std::make_shared<int32_t>((int32_t)pJson["qty"].asInt64());
        }
    }
    if(pJson.isMember("medical_facility_id"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["medical_facility_id"].isNull())
        {
            medicalFacilityId_=std::make_shared<int64_t>((int64_t)pJson["medical_facility_id"].asInt64());
        }
    }
    if(pJson.isMember("courir_id"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["courir_id"].isNull())
        {
            courirId_=std::make_shared<int64_t>((int64_t)pJson["courir_id"].asInt64());
        }
    }
    if(pJson.isMember("sub_total"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["sub_total"].isNull())
        {
            subTotal_=std::make_shared<std::string>(pJson["sub_total"].asString());
        }
    }
    if(pJson.isMember("created_by"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["created_by"].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson["created_by"].asInt64());
        }
    }
    if(pJson.isMember("created_on"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["created_on"].isNull())
        {
            auto timeStr = pJson["created_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("modified_by"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["modified_by"].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson["modified_by"].asInt64());
        }
    }
    if(pJson.isMember("modified_on"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["modified_on"].isNull())
        {
            auto timeStr = pJson["modified_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("deleted_by"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["deleted_by"].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson["deleted_by"].asInt64());
        }
    }
    if(pJson.isMember("deleted_on"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["deleted_on"].isNull())
        {
            auto timeStr = pJson["deleted_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("is_delete"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["is_delete"].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson["is_delete"].asBool());
        }
    }
}

const int64_t &TMedicalItemPurchaseDetail::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TMedicalItemPurchaseDetail::getId() const noexcept
{
    return id_;
}
void TMedicalItemPurchaseDetail::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename TMedicalItemPurchaseDetail::PrimaryKeyType & TMedicalItemPurchaseDetail::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &TMedicalItemPurchaseDetail::getValueOfMedicalItemPurchaseId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(medicalItemPurchaseId_)
        return *medicalItemPurchaseId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TMedicalItemPurchaseDetail::getMedicalItemPurchaseId() const noexcept
{
    return medicalItemPurchaseId_;
}
void TMedicalItemPurchaseDetail::setMedicalItemPurchaseId(const int64_t &pMedicalItemPurchaseId) noexcept
{
    medicalItemPurchaseId_ = std::make_shared<int64_t>(pMedicalItemPurchaseId);
    dirtyFlag_[1] = true;
}
void TMedicalItemPurchaseDetail::setMedicalItemPurchaseIdToNull() noexcept
{
    medicalItemPurchaseId_.reset();
    dirtyFlag_[1] = true;
}

const int64_t &TMedicalItemPurchaseDetail::getValueOfMedicalItemId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(medicalItemId_)
        return *medicalItemId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TMedicalItemPurchaseDetail::getMedicalItemId() const noexcept
{
    return medicalItemId_;
}
void TMedicalItemPurchaseDetail::setMedicalItemId(const int64_t &pMedicalItemId) noexcept
{
    medicalItemId_ = std::make_shared<int64_t>(pMedicalItemId);
    dirtyFlag_[2] = true;
}
void TMedicalItemPurchaseDetail::setMedicalItemIdToNull() noexcept
{
    medicalItemId_.reset();
    dirtyFlag_[2] = true;
}

const int32_t &TMedicalItemPurchaseDetail::getValueOfQty() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(qty_)
        return *qty_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &TMedicalItemPurchaseDetail::getQty() const noexcept
{
    return qty_;
}
void TMedicalItemPurchaseDetail::setQty(const int32_t &pQty) noexcept
{
    qty_ = std::make_shared<int32_t>(pQty);
    dirtyFlag_[3] = true;
}
void TMedicalItemPurchaseDetail::setQtyToNull() noexcept
{
    qty_.reset();
    dirtyFlag_[3] = true;
}

const int64_t &TMedicalItemPurchaseDetail::getValueOfMedicalFacilityId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(medicalFacilityId_)
        return *medicalFacilityId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TMedicalItemPurchaseDetail::getMedicalFacilityId() const noexcept
{
    return medicalFacilityId_;
}
void TMedicalItemPurchaseDetail::setMedicalFacilityId(const int64_t &pMedicalFacilityId) noexcept
{
    medicalFacilityId_ = std::make_shared<int64_t>(pMedicalFacilityId);
    dirtyFlag_[4] = true;
}
void TMedicalItemPurchaseDetail::setMedicalFacilityIdToNull() noexcept
{
    medicalFacilityId_.reset();
    dirtyFlag_[4] = true;
}

const int64_t &TMedicalItemPurchaseDetail::getValueOfCourirId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(courirId_)
        return *courirId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TMedicalItemPurchaseDetail::getCourirId() const noexcept
{
    return courirId_;
}
void TMedicalItemPurchaseDetail::setCourirId(const int64_t &pCourirId) noexcept
{
    courirId_ = std::make_shared<int64_t>(pCourirId);
    dirtyFlag_[5] = true;
}
void TMedicalItemPurchaseDetail::setCourirIdToNull() noexcept
{
    courirId_.reset();
    dirtyFlag_[5] = true;
}

const std::string &TMedicalItemPurchaseDetail::getValueOfSubTotal() const noexcept
{
    static const std::string defaultValue = std::string();
    if(subTotal_)
        return *subTotal_;
    return defaultValue;
}
const std::shared_ptr<std::string> &TMedicalItemPurchaseDetail::getSubTotal() const noexcept
{
    return subTotal_;
}
void TMedicalItemPurchaseDetail::setSubTotal(const std::string &pSubTotal) noexcept
{
    subTotal_ = std::make_shared<std::string>(pSubTotal);
    dirtyFlag_[6] = true;
}
void TMedicalItemPurchaseDetail::setSubTotal(std::string &&pSubTotal) noexcept
{
    subTotal_ = std::make_shared<std::string>(std::move(pSubTotal));
    dirtyFlag_[6] = true;
}
void TMedicalItemPurchaseDetail::setSubTotalToNull() noexcept
{
    subTotal_.reset();
    dirtyFlag_[6] = true;
}

const int64_t &TMedicalItemPurchaseDetail::getValueOfCreatedBy() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(createdBy_)
        return *createdBy_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TMedicalItemPurchaseDetail::getCreatedBy() const noexcept
{
    return createdBy_;
}
void TMedicalItemPurchaseDetail::setCreatedBy(const int64_t &pCreatedBy) noexcept
{
    createdBy_ = std::make_shared<int64_t>(pCreatedBy);
    dirtyFlag_[7] = true;
}

const ::trantor::Date &TMedicalItemPurchaseDetail::getValueOfCreatedOn() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdOn_)
        return *createdOn_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &TMedicalItemPurchaseDetail::getCreatedOn() const noexcept
{
    return createdOn_;
}
void TMedicalItemPurchaseDetail::setCreatedOn(const ::trantor::Date &pCreatedOn) noexcept
{
    createdOn_ = std::make_shared<::trantor::Date>(pCreatedOn);
    dirtyFlag_[8] = true;
}

const int64_t &TMedicalItemPurchaseDetail::getValueOfModifiedBy() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(modifiedBy_)
        return *modifiedBy_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TMedicalItemPurchaseDetail::getModifiedBy() const noexcept
{
    return modifiedBy_;
}
void TMedicalItemPurchaseDetail::setModifiedBy(const int64_t &pModifiedBy) noexcept
{
    modifiedBy_ = std::make_shared<int64_t>(pModifiedBy);
    dirtyFlag_[9] = true;
}
void TMedicalItemPurchaseDetail::setModifiedByToNull() noexcept
{
    modifiedBy_.reset();
    dirtyFlag_[9] = true;
}

const ::trantor::Date &TMedicalItemPurchaseDetail::getValueOfModifiedOn() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(modifiedOn_)
        return *modifiedOn_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &TMedicalItemPurchaseDetail::getModifiedOn() const noexcept
{
    return modifiedOn_;
}
void TMedicalItemPurchaseDetail::setModifiedOn(const ::trantor::Date &pModifiedOn) noexcept
{
    modifiedOn_ = std::make_shared<::trantor::Date>(pModifiedOn);
    dirtyFlag_[10] = true;
}
void TMedicalItemPurchaseDetail::setModifiedOnToNull() noexcept
{
    modifiedOn_.reset();
    dirtyFlag_[10] = true;
}

const int64_t &TMedicalItemPurchaseDetail::getValueOfDeletedBy() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(deletedBy_)
        return *deletedBy_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TMedicalItemPurchaseDetail::getDeletedBy() const noexcept
{
    return deletedBy_;
}
void TMedicalItemPurchaseDetail::setDeletedBy(const int64_t &pDeletedBy) noexcept
{
    deletedBy_ = std::make_shared<int64_t>(pDeletedBy);
    dirtyFlag_[11] = true;
}
void TMedicalItemPurchaseDetail::setDeletedByToNull() noexcept
{
    deletedBy_.reset();
    dirtyFlag_[11] = true;
}

const ::trantor::Date &TMedicalItemPurchaseDetail::getValueOfDeletedOn() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(deletedOn_)
        return *deletedOn_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &TMedicalItemPurchaseDetail::getDeletedOn() const noexcept
{
    return deletedOn_;
}
void TMedicalItemPurchaseDetail::setDeletedOn(const ::trantor::Date &pDeletedOn) noexcept
{
    deletedOn_ = std::make_shared<::trantor::Date>(pDeletedOn);
    dirtyFlag_[12] = true;
}
void TMedicalItemPurchaseDetail::setDeletedOnToNull() noexcept
{
    deletedOn_.reset();
    dirtyFlag_[12] = true;
}

const bool &TMedicalItemPurchaseDetail::getValueOfIsDelete() const noexcept
{
    static const bool defaultValue = bool();
    if(isDelete_)
        return *isDelete_;
    return defaultValue;
}
const std::shared_ptr<bool> &TMedicalItemPurchaseDetail::getIsDelete() const noexcept
{
    return isDelete_;
}
void TMedicalItemPurchaseDetail::setIsDelete(const bool &pIsDelete) noexcept
{
    isDelete_ = std::make_shared<bool>(pIsDelete);
    dirtyFlag_[13] = true;
}

void TMedicalItemPurchaseDetail::updateId(const uint64_t id)
{
}

const std::vector<std::string> &TMedicalItemPurchaseDetail::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "medical_item_purchase_id",
        "medical_item_id",
        "qty",
        "medical_facility_id",
        "courir_id",
        "sub_total",
        "created_by",
        "created_on",
        "modified_by",
        "modified_on",
        "deleted_by",
        "deleted_on",
        "is_delete"
    };
    return inCols;
}

void TMedicalItemPurchaseDetail::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMedicalItemPurchaseId())
        {
            binder << getValueOfMedicalItemPurchaseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMedicalItemId())
        {
            binder << getValueOfMedicalItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getQty())
        {
            binder << getValueOfQty();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getMedicalFacilityId())
        {
            binder << getValueOfMedicalFacilityId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCourirId())
        {
            binder << getValueOfCourirId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getSubTotal())
        {
            binder << getValueOfSubTotal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedBy())
        {
            binder << getValueOfCreatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getCreatedOn())
        {
            binder << getValueOfCreatedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getModifiedBy())
        {
            binder << getValueOfModifiedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getModifiedOn())
        {
            binder << getValueOfModifiedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getDeletedBy())
        {
            binder << getValueOfDeletedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getDeletedOn())
        {
            binder << getValueOfDeletedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getIsDelete())
        {
            binder << getValueOfIsDelete();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> TMedicalItemPurchaseDetail::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    return ret;
}

void TMedicalItemPurchaseDetail::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMedicalItemPurchaseId())
        {
            binder << getValueOfMedicalItemPurchaseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMedicalItemId())
        {
            binder << getValueOfMedicalItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getQty())
        {
            binder << getValueOfQty();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getMedicalFacilityId())
        {
            binder << getValueOfMedicalFacilityId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCourirId())
        {
            binder << getValueOfCourirId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getSubTotal())
        {
            binder << getValueOfSubTotal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedBy())
        {
            binder << getValueOfCreatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getCreatedOn())
        {
            binder << getValueOfCreatedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getModifiedBy())
        {
            binder << getValueOfModifiedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getModifiedOn())
        {
            binder << getValueOfModifiedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getDeletedBy())
        {
            binder << getValueOfDeletedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getDeletedOn())
        {
            binder << getValueOfDeletedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getIsDelete())
        {
            binder << getValueOfIsDelete();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value TMedicalItemPurchaseDetail::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMedicalItemPurchaseId())
    {
        ret["medical_item_purchase_id"]=(Json::Int64)getValueOfMedicalItemPurchaseId();
    }
    else
    {
        ret["medical_item_purchase_id"]=Json::Value();
    }
    if(getMedicalItemId())
    {
        ret["medical_item_id"]=(Json::Int64)getValueOfMedicalItemId();
    }
    else
    {
        ret["medical_item_id"]=Json::Value();
    }
    if(getQty())
    {
        ret["qty"]=getValueOfQty();
    }
    else
    {
        ret["qty"]=Json::Value();
    }
    if(getMedicalFacilityId())
    {
        ret["medical_facility_id"]=(Json::Int64)getValueOfMedicalFacilityId();
    }
    else
    {
        ret["medical_facility_id"]=Json::Value();
    }
    if(getCourirId())
    {
        ret["courir_id"]=(Json::Int64)getValueOfCourirId();
    }
    else
    {
        ret["courir_id"]=Json::Value();
    }
    if(getSubTotal())
    {
        ret["sub_total"]=getValueOfSubTotal();
    }
    else
    {
        ret["sub_total"]=Json::Value();
    }
    if(getCreatedBy())
    {
        ret["created_by"]=(Json::Int64)getValueOfCreatedBy();
    }
    else
    {
        ret["created_by"]=Json::Value();
    }
    if(getCreatedOn())
    {
        ret["created_on"]=getCreatedOn()->toDbStringLocal();
    }
    else
    {
        ret["created_on"]=Json::Value();
    }
    if(getModifiedBy())
    {
        ret["modified_by"]=(Json::Int64)getValueOfModifiedBy();
    }
    else
    {
        ret["modified_by"]=Json::Value();
    }
    if(getModifiedOn())
    {
        ret["modified_on"]=getModifiedOn()->toDbStringLocal();
    }
    else
    {
        ret["modified_on"]=Json::Value();
    }
    if(getDeletedBy())
    {
        ret["deleted_by"]=(Json::Int64)getValueOfDeletedBy();
    }
    else
    {
        ret["deleted_by"]=Json::Value();
    }
    if(getDeletedOn())
    {
        ret["deleted_on"]=getDeletedOn()->toDbStringLocal();
    }
    else
    {
        ret["deleted_on"]=Json::Value();
    }
    if(getIsDelete())
    {
        ret["is_delete"]=getValueOfIsDelete();
    }
    else
    {
        ret["is_delete"]=Json::Value();
    }
    return ret;
}

Json::Value TMedicalItemPurchaseDetail::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 14)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getMedicalItemPurchaseId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfMedicalItemPurchaseId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getMedicalItemId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfMedicalItemId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getQty())
            {
                ret[pMasqueradingVector[3]]=getValueOfQty();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getMedicalFacilityId())
            {
                ret[pMasqueradingVector[4]]=(Json::Int64)getValueOfMedicalFacilityId();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getCourirId())
            {
                ret[pMasqueradingVector[5]]=(Json::Int64)getValueOfCourirId();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getSubTotal())
            {
                ret[pMasqueradingVector[6]]=getValueOfSubTotal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getCreatedBy())
            {
                ret[pMasqueradingVector[7]]=(Json::Int64)getValueOfCreatedBy();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getCreatedOn())
            {
                ret[pMasqueradingVector[8]]=getCreatedOn()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getModifiedBy())
            {
                ret[pMasqueradingVector[9]]=(Json::Int64)getValueOfModifiedBy();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getModifiedOn())
            {
                ret[pMasqueradingVector[10]]=getModifiedOn()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getDeletedBy())
            {
                ret[pMasqueradingVector[11]]=(Json::Int64)getValueOfDeletedBy();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getDeletedOn())
            {
                ret[pMasqueradingVector[12]]=getDeletedOn()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getIsDelete())
            {
                ret[pMasqueradingVector[13]]=getValueOfIsDelete();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMedicalItemPurchaseId())
    {
        ret["medical_item_purchase_id"]=(Json::Int64)getValueOfMedicalItemPurchaseId();
    }
    else
    {
        ret["medical_item_purchase_id"]=Json::Value();
    }
    if(getMedicalItemId())
    {
        ret["medical_item_id"]=(Json::Int64)getValueOfMedicalItemId();
    }
    else
    {
        ret["medical_item_id"]=Json::Value();
    }
    if(getQty())
    {
        ret["qty"]=getValueOfQty();
    }
    else
    {
        ret["qty"]=Json::Value();
    }
    if(getMedicalFacilityId())
    {
        ret["medical_facility_id"]=(Json::Int64)getValueOfMedicalFacilityId();
    }
    else
    {
        ret["medical_facility_id"]=Json::Value();
    }
    if(getCourirId())
    {
        ret["courir_id"]=(Json::Int64)getValueOfCourirId();
    }
    else
    {
        ret["courir_id"]=Json::Value();
    }
    if(getSubTotal())
    {
        ret["sub_total"]=getValueOfSubTotal();
    }
    else
    {
        ret["sub_total"]=Json::Value();
    }
    if(getCreatedBy())
    {
        ret["created_by"]=(Json::Int64)getValueOfCreatedBy();
    }
    else
    {
        ret["created_by"]=Json::Value();
    }
    if(getCreatedOn())
    {
        ret["created_on"]=getCreatedOn()->toDbStringLocal();
    }
    else
    {
        ret["created_on"]=Json::Value();
    }
    if(getModifiedBy())
    {
        ret["modified_by"]=(Json::Int64)getValueOfModifiedBy();
    }
    else
    {
        ret["modified_by"]=Json::Value();
    }
    if(getModifiedOn())
    {
        ret["modified_on"]=getModifiedOn()->toDbStringLocal();
    }
    else
    {
        ret["modified_on"]=Json::Value();
    }
    if(getDeletedBy())
    {
        ret["deleted_by"]=(Json::Int64)getValueOfDeletedBy();
    }
    else
    {
        ret["deleted_by"]=Json::Value();
    }
    if(getDeletedOn())
    {
        ret["deleted_on"]=getDeletedOn()->toDbStringLocal();
    }
    else
    {
        ret["deleted_on"]=Json::Value();
    }
    if(getIsDelete())
    {
        ret["is_delete"]=getValueOfIsDelete();
    }
    else
    {
        ret["is_delete"]=Json::Value();
    }
    return ret;
}

bool TMedicalItemPurchaseDetail::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("medical_item_purchase_id"))
    {
        if(!validJsonOfField(1, "medical_item_purchase_id", pJson["medical_item_purchase_id"], err, true))
            return false;
    }
    if(pJson.isMember("medical_item_id"))
    {
        if(!validJsonOfField(2, "medical_item_id", pJson["medical_item_id"], err, true))
            return false;
    }
    if(pJson.isMember("qty"))
    {
        if(!validJsonOfField(3, "qty", pJson["qty"], err, true))
            return false;
    }
    if(pJson.isMember("medical_facility_id"))
    {
        if(!validJsonOfField(4, "medical_facility_id", pJson["medical_facility_id"], err, true))
            return false;
    }
    if(pJson.isMember("courir_id"))
    {
        if(!validJsonOfField(5, "courir_id", pJson["courir_id"], err, true))
            return false;
    }
    if(pJson.isMember("sub_total"))
    {
        if(!validJsonOfField(6, "sub_total", pJson["sub_total"], err, true))
            return false;
    }
    if(pJson.isMember("created_by"))
    {
        if(!validJsonOfField(7, "created_by", pJson["created_by"], err, true))
            return false;
    }
    else
    {
        err="The created_by column cannot be null";
        return false;
    }
    if(pJson.isMember("created_on"))
    {
        if(!validJsonOfField(8, "created_on", pJson["created_on"], err, true))
            return false;
    }
    else
    {
        err="The created_on column cannot be null";
        return false;
    }
    if(pJson.isMember("modified_by"))
    {
        if(!validJsonOfField(9, "modified_by", pJson["modified_by"], err, true))
            return false;
    }
    if(pJson.isMember("modified_on"))
    {
        if(!validJsonOfField(10, "modified_on", pJson["modified_on"], err, true))
            return false;
    }
    if(pJson.isMember("deleted_by"))
    {
        if(!validJsonOfField(11, "deleted_by", pJson["deleted_by"], err, true))
            return false;
    }
    if(pJson.isMember("deleted_on"))
    {
        if(!validJsonOfField(12, "deleted_on", pJson["deleted_on"], err, true))
            return false;
    }
    if(pJson.isMember("is_delete"))
    {
        if(!validJsonOfField(13, "is_delete", pJson["is_delete"], err, true))
            return false;
    }
    return true;
}
bool TMedicalItemPurchaseDetail::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                                    const std::vector<std::string> &pMasqueradingVector,
                                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[8] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TMedicalItemPurchaseDetail::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("medical_item_purchase_id"))
    {
        if(!validJsonOfField(1, "medical_item_purchase_id", pJson["medical_item_purchase_id"], err, false))
            return false;
    }
    if(pJson.isMember("medical_item_id"))
    {
        if(!validJsonOfField(2, "medical_item_id", pJson["medical_item_id"], err, false))
            return false;
    }
    if(pJson.isMember("qty"))
    {
        if(!validJsonOfField(3, "qty", pJson["qty"], err, false))
            return false;
    }
    if(pJson.isMember("medical_facility_id"))
    {
        if(!validJsonOfField(4, "medical_facility_id", pJson["medical_facility_id"], err, false))
            return false;
    }
    if(pJson.isMember("courir_id"))
    {
        if(!validJsonOfField(5, "courir_id", pJson["courir_id"], err, false))
            return false;
    }
    if(pJson.isMember("sub_total"))
    {
        if(!validJsonOfField(6, "sub_total", pJson["sub_total"], err, false))
            return false;
    }
    if(pJson.isMember("created_by"))
    {
        if(!validJsonOfField(7, "created_by", pJson["created_by"], err, false))
            return false;
    }
    if(pJson.isMember("created_on"))
    {
        if(!validJsonOfField(8, "created_on", pJson["created_on"], err, false))
            return false;
    }
    if(pJson.isMember("modified_by"))
    {
        if(!validJsonOfField(9, "modified_by", pJson["modified_by"], err, false))
            return false;
    }
    if(pJson.isMember("modified_on"))
    {
        if(!validJsonOfField(10, "modified_on", pJson["modified_on"], err, false))
            return false;
    }
    if(pJson.isMember("deleted_by"))
    {
        if(!validJsonOfField(11, "deleted_by", pJson["deleted_by"], err, false))
            return false;
    }
    if(pJson.isMember("deleted_on"))
    {
        if(!validJsonOfField(12, "deleted_on", pJson["deleted_on"], err, false))
            return false;
    }
    if(pJson.isMember("is_delete"))
    {
        if(!validJsonOfField(13, "is_delete", pJson["is_delete"], err, false))
            return false;
    }
    return true;
}
bool TMedicalItemPurchaseDetail::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                                  const std::vector<std::string> &pMasqueradingVector,
                                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TMedicalItemPurchaseDetail::validJsonOfField(size_t index,
                                                  const std::string &fieldName,
                                                  const Json::Value &pJson,
                                                  std::string &err,
                                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
