/**
 *
 *  TTreatmentDiscount.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "TTreatmentDiscount.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::db_hospital;

const std::string TTreatmentDiscount::Cols::_id = "id";
const std::string TTreatmentDiscount::Cols::_doctor_office_treatment_price_id = "doctor_office_treatment_price_id";
const std::string TTreatmentDiscount::Cols::_value = "value";
const std::string TTreatmentDiscount::Cols::_created_by = "created_by";
const std::string TTreatmentDiscount::Cols::_created_on = "created_on";
const std::string TTreatmentDiscount::Cols::_modified_by = "modified_by";
const std::string TTreatmentDiscount::Cols::_modified_on = "modified_on";
const std::string TTreatmentDiscount::Cols::_deleted_by = "deleted_by";
const std::string TTreatmentDiscount::Cols::_deleted_on = "deleted_on";
const std::string TTreatmentDiscount::Cols::_is_delete = "is_delete";
const std::string TTreatmentDiscount::primaryKeyName = "id";
const bool TTreatmentDiscount::hasPrimaryKey = true;
const std::string TTreatmentDiscount::tableName = "t_treatment_discount";

const std::vector<typename TTreatmentDiscount::MetaData> TTreatmentDiscount::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"doctor_office_treatment_price_id","int64_t","bigint",8,0,0,0},
{"value","std::string","numeric",0,0,0,0},
{"created_by","int64_t","bigint",8,0,0,1},
{"created_on","::trantor::Date","timestamp without time zone",0,0,0,1},
{"modified_by","int64_t","bigint",8,0,0,0},
{"modified_on","::trantor::Date","timestamp without time zone",0,0,0,0},
{"deleted_by","int64_t","bigint",8,0,0,0},
{"deleted_on","::trantor::Date","timestamp without time zone",0,0,0,0},
{"is_delete","bool","boolean",1,0,0,1}
};
const std::string &TTreatmentDiscount::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
TTreatmentDiscount::TTreatmentDiscount(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["doctor_office_treatment_price_id"].isNull())
        {
            doctorOfficeTreatmentPriceId_=std::make_shared<int64_t>(r["doctor_office_treatment_price_id"].as<int64_t>());
        }
        if(!r["value"].isNull())
        {
            value_=std::make_shared<std::string>(r["value"].as<std::string>());
        }
        if(!r["created_by"].isNull())
        {
            createdBy_=std::make_shared<int64_t>(r["created_by"].as<int64_t>());
        }
        if(!r["created_on"].isNull())
        {
            auto timeStr = r["created_on"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["modified_by"].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>(r["modified_by"].as<int64_t>());
        }
        if(!r["modified_on"].isNull())
        {
            auto timeStr = r["modified_on"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["deleted_by"].isNull())
        {
            deletedBy_=std::make_shared<int64_t>(r["deleted_by"].as<int64_t>());
        }
        if(!r["deleted_on"].isNull())
        {
            auto timeStr = r["deleted_on"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["is_delete"].isNull())
        {
            isDelete_=std::make_shared<bool>(r["is_delete"].as<bool>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 10 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            doctorOfficeTreatmentPriceId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            value_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            createdBy_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            deletedBy_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            isDelete_=std::make_shared<bool>(r[index].as<bool>());
        }
    }

}

TTreatmentDiscount::TTreatmentDiscount(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            doctorOfficeTreatmentPriceId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            value_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson[pMasqueradingVector[9]].asBool());
        }
    }
}

TTreatmentDiscount::TTreatmentDiscount(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("doctor_office_treatment_price_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["doctor_office_treatment_price_id"].isNull())
        {
            doctorOfficeTreatmentPriceId_=std::make_shared<int64_t>((int64_t)pJson["doctor_office_treatment_price_id"].asInt64());
        }
    }
    if(pJson.isMember("value"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["value"].isNull())
        {
            value_=std::make_shared<std::string>(pJson["value"].asString());
        }
    }
    if(pJson.isMember("created_by"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["created_by"].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson["created_by"].asInt64());
        }
    }
    if(pJson.isMember("created_on"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["created_on"].isNull())
        {
            auto timeStr = pJson["created_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("modified_by"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["modified_by"].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson["modified_by"].asInt64());
        }
    }
    if(pJson.isMember("modified_on"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["modified_on"].isNull())
        {
            auto timeStr = pJson["modified_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("deleted_by"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["deleted_by"].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson["deleted_by"].asInt64());
        }
    }
    if(pJson.isMember("deleted_on"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["deleted_on"].isNull())
        {
            auto timeStr = pJson["deleted_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("is_delete"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["is_delete"].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson["is_delete"].asBool());
        }
    }
}

void TTreatmentDiscount::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            doctorOfficeTreatmentPriceId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            value_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson[pMasqueradingVector[9]].asBool());
        }
    }
}

void TTreatmentDiscount::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("doctor_office_treatment_price_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["doctor_office_treatment_price_id"].isNull())
        {
            doctorOfficeTreatmentPriceId_=std::make_shared<int64_t>((int64_t)pJson["doctor_office_treatment_price_id"].asInt64());
        }
    }
    if(pJson.isMember("value"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["value"].isNull())
        {
            value_=std::make_shared<std::string>(pJson["value"].asString());
        }
    }
    if(pJson.isMember("created_by"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["created_by"].isNull())
        {
            createdBy_=std::make_shared<int64_t>((int64_t)pJson["created_by"].asInt64());
        }
    }
    if(pJson.isMember("created_on"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["created_on"].isNull())
        {
            auto timeStr = pJson["created_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("modified_by"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["modified_by"].isNull())
        {
            modifiedBy_=std::make_shared<int64_t>((int64_t)pJson["modified_by"].asInt64());
        }
    }
    if(pJson.isMember("modified_on"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["modified_on"].isNull())
        {
            auto timeStr = pJson["modified_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifiedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("deleted_by"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["deleted_by"].isNull())
        {
            deletedBy_=std::make_shared<int64_t>((int64_t)pJson["deleted_by"].asInt64());
        }
    }
    if(pJson.isMember("deleted_on"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["deleted_on"].isNull())
        {
            auto timeStr = pJson["deleted_on"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deletedOn_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("is_delete"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["is_delete"].isNull())
        {
            isDelete_=std::make_shared<bool>(pJson["is_delete"].asBool());
        }
    }
}

const int64_t &TTreatmentDiscount::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TTreatmentDiscount::getId() const noexcept
{
    return id_;
}
void TTreatmentDiscount::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename TTreatmentDiscount::PrimaryKeyType & TTreatmentDiscount::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &TTreatmentDiscount::getValueOfDoctorOfficeTreatmentPriceId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(doctorOfficeTreatmentPriceId_)
        return *doctorOfficeTreatmentPriceId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TTreatmentDiscount::getDoctorOfficeTreatmentPriceId() const noexcept
{
    return doctorOfficeTreatmentPriceId_;
}
void TTreatmentDiscount::setDoctorOfficeTreatmentPriceId(const int64_t &pDoctorOfficeTreatmentPriceId) noexcept
{
    doctorOfficeTreatmentPriceId_ = std::make_shared<int64_t>(pDoctorOfficeTreatmentPriceId);
    dirtyFlag_[1] = true;
}
void TTreatmentDiscount::setDoctorOfficeTreatmentPriceIdToNull() noexcept
{
    doctorOfficeTreatmentPriceId_.reset();
    dirtyFlag_[1] = true;
}

const std::string &TTreatmentDiscount::getValueOfValue() const noexcept
{
    static const std::string defaultValue = std::string();
    if(value_)
        return *value_;
    return defaultValue;
}
const std::shared_ptr<std::string> &TTreatmentDiscount::getValue() const noexcept
{
    return value_;
}
void TTreatmentDiscount::setValue(const std::string &pValue) noexcept
{
    value_ = std::make_shared<std::string>(pValue);
    dirtyFlag_[2] = true;
}
void TTreatmentDiscount::setValue(std::string &&pValue) noexcept
{
    value_ = std::make_shared<std::string>(std::move(pValue));
    dirtyFlag_[2] = true;
}
void TTreatmentDiscount::setValueToNull() noexcept
{
    value_.reset();
    dirtyFlag_[2] = true;
}

const int64_t &TTreatmentDiscount::getValueOfCreatedBy() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(createdBy_)
        return *createdBy_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TTreatmentDiscount::getCreatedBy() const noexcept
{
    return createdBy_;
}
void TTreatmentDiscount::setCreatedBy(const int64_t &pCreatedBy) noexcept
{
    createdBy_ = std::make_shared<int64_t>(pCreatedBy);
    dirtyFlag_[3] = true;
}

const ::trantor::Date &TTreatmentDiscount::getValueOfCreatedOn() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdOn_)
        return *createdOn_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &TTreatmentDiscount::getCreatedOn() const noexcept
{
    return createdOn_;
}
void TTreatmentDiscount::setCreatedOn(const ::trantor::Date &pCreatedOn) noexcept
{
    createdOn_ = std::make_shared<::trantor::Date>(pCreatedOn);
    dirtyFlag_[4] = true;
}

const int64_t &TTreatmentDiscount::getValueOfModifiedBy() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(modifiedBy_)
        return *modifiedBy_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TTreatmentDiscount::getModifiedBy() const noexcept
{
    return modifiedBy_;
}
void TTreatmentDiscount::setModifiedBy(const int64_t &pModifiedBy) noexcept
{
    modifiedBy_ = std::make_shared<int64_t>(pModifiedBy);
    dirtyFlag_[5] = true;
}
void TTreatmentDiscount::setModifiedByToNull() noexcept
{
    modifiedBy_.reset();
    dirtyFlag_[5] = true;
}

const ::trantor::Date &TTreatmentDiscount::getValueOfModifiedOn() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(modifiedOn_)
        return *modifiedOn_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &TTreatmentDiscount::getModifiedOn() const noexcept
{
    return modifiedOn_;
}
void TTreatmentDiscount::setModifiedOn(const ::trantor::Date &pModifiedOn) noexcept
{
    modifiedOn_ = std::make_shared<::trantor::Date>(pModifiedOn);
    dirtyFlag_[6] = true;
}
void TTreatmentDiscount::setModifiedOnToNull() noexcept
{
    modifiedOn_.reset();
    dirtyFlag_[6] = true;
}

const int64_t &TTreatmentDiscount::getValueOfDeletedBy() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(deletedBy_)
        return *deletedBy_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TTreatmentDiscount::getDeletedBy() const noexcept
{
    return deletedBy_;
}
void TTreatmentDiscount::setDeletedBy(const int64_t &pDeletedBy) noexcept
{
    deletedBy_ = std::make_shared<int64_t>(pDeletedBy);
    dirtyFlag_[7] = true;
}
void TTreatmentDiscount::setDeletedByToNull() noexcept
{
    deletedBy_.reset();
    dirtyFlag_[7] = true;
}

const ::trantor::Date &TTreatmentDiscount::getValueOfDeletedOn() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(deletedOn_)
        return *deletedOn_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &TTreatmentDiscount::getDeletedOn() const noexcept
{
    return deletedOn_;
}
void TTreatmentDiscount::setDeletedOn(const ::trantor::Date &pDeletedOn) noexcept
{
    deletedOn_ = std::make_shared<::trantor::Date>(pDeletedOn);
    dirtyFlag_[8] = true;
}
void TTreatmentDiscount::setDeletedOnToNull() noexcept
{
    deletedOn_.reset();
    dirtyFlag_[8] = true;
}

const bool &TTreatmentDiscount::getValueOfIsDelete() const noexcept
{
    static const bool defaultValue = bool();
    if(isDelete_)
        return *isDelete_;
    return defaultValue;
}
const std::shared_ptr<bool> &TTreatmentDiscount::getIsDelete() const noexcept
{
    return isDelete_;
}
void TTreatmentDiscount::setIsDelete(const bool &pIsDelete) noexcept
{
    isDelete_ = std::make_shared<bool>(pIsDelete);
    dirtyFlag_[9] = true;
}

void TTreatmentDiscount::updateId(const uint64_t id)
{
}

const std::vector<std::string> &TTreatmentDiscount::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "doctor_office_treatment_price_id",
        "value",
        "created_by",
        "created_on",
        "modified_by",
        "modified_on",
        "deleted_by",
        "deleted_on",
        "is_delete"
    };
    return inCols;
}

void TTreatmentDiscount::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getDoctorOfficeTreatmentPriceId())
        {
            binder << getValueOfDoctorOfficeTreatmentPriceId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getValue())
        {
            binder << getValueOfValue();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCreatedBy())
        {
            binder << getValueOfCreatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCreatedOn())
        {
            binder << getValueOfCreatedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getModifiedBy())
        {
            binder << getValueOfModifiedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getModifiedOn())
        {
            binder << getValueOfModifiedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDeletedBy())
        {
            binder << getValueOfDeletedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getDeletedOn())
        {
            binder << getValueOfDeletedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getIsDelete())
        {
            binder << getValueOfIsDelete();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> TTreatmentDiscount::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    return ret;
}

void TTreatmentDiscount::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getDoctorOfficeTreatmentPriceId())
        {
            binder << getValueOfDoctorOfficeTreatmentPriceId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getValue())
        {
            binder << getValueOfValue();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCreatedBy())
        {
            binder << getValueOfCreatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCreatedOn())
        {
            binder << getValueOfCreatedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getModifiedBy())
        {
            binder << getValueOfModifiedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getModifiedOn())
        {
            binder << getValueOfModifiedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDeletedBy())
        {
            binder << getValueOfDeletedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getDeletedOn())
        {
            binder << getValueOfDeletedOn();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getIsDelete())
        {
            binder << getValueOfIsDelete();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value TTreatmentDiscount::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getDoctorOfficeTreatmentPriceId())
    {
        ret["doctor_office_treatment_price_id"]=(Json::Int64)getValueOfDoctorOfficeTreatmentPriceId();
    }
    else
    {
        ret["doctor_office_treatment_price_id"]=Json::Value();
    }
    if(getValue())
    {
        ret["value"]=getValueOfValue();
    }
    else
    {
        ret["value"]=Json::Value();
    }
    if(getCreatedBy())
    {
        ret["created_by"]=(Json::Int64)getValueOfCreatedBy();
    }
    else
    {
        ret["created_by"]=Json::Value();
    }
    if(getCreatedOn())
    {
        ret["created_on"]=getCreatedOn()->toDbStringLocal();
    }
    else
    {
        ret["created_on"]=Json::Value();
    }
    if(getModifiedBy())
    {
        ret["modified_by"]=(Json::Int64)getValueOfModifiedBy();
    }
    else
    {
        ret["modified_by"]=Json::Value();
    }
    if(getModifiedOn())
    {
        ret["modified_on"]=getModifiedOn()->toDbStringLocal();
    }
    else
    {
        ret["modified_on"]=Json::Value();
    }
    if(getDeletedBy())
    {
        ret["deleted_by"]=(Json::Int64)getValueOfDeletedBy();
    }
    else
    {
        ret["deleted_by"]=Json::Value();
    }
    if(getDeletedOn())
    {
        ret["deleted_on"]=getDeletedOn()->toDbStringLocal();
    }
    else
    {
        ret["deleted_on"]=Json::Value();
    }
    if(getIsDelete())
    {
        ret["is_delete"]=getValueOfIsDelete();
    }
    else
    {
        ret["is_delete"]=Json::Value();
    }
    return ret;
}

Json::Value TTreatmentDiscount::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 10)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getDoctorOfficeTreatmentPriceId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfDoctorOfficeTreatmentPriceId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getValue())
            {
                ret[pMasqueradingVector[2]]=getValueOfValue();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getCreatedBy())
            {
                ret[pMasqueradingVector[3]]=(Json::Int64)getValueOfCreatedBy();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getCreatedOn())
            {
                ret[pMasqueradingVector[4]]=getCreatedOn()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getModifiedBy())
            {
                ret[pMasqueradingVector[5]]=(Json::Int64)getValueOfModifiedBy();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getModifiedOn())
            {
                ret[pMasqueradingVector[6]]=getModifiedOn()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getDeletedBy())
            {
                ret[pMasqueradingVector[7]]=(Json::Int64)getValueOfDeletedBy();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getDeletedOn())
            {
                ret[pMasqueradingVector[8]]=getDeletedOn()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getIsDelete())
            {
                ret[pMasqueradingVector[9]]=getValueOfIsDelete();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getDoctorOfficeTreatmentPriceId())
    {
        ret["doctor_office_treatment_price_id"]=(Json::Int64)getValueOfDoctorOfficeTreatmentPriceId();
    }
    else
    {
        ret["doctor_office_treatment_price_id"]=Json::Value();
    }
    if(getValue())
    {
        ret["value"]=getValueOfValue();
    }
    else
    {
        ret["value"]=Json::Value();
    }
    if(getCreatedBy())
    {
        ret["created_by"]=(Json::Int64)getValueOfCreatedBy();
    }
    else
    {
        ret["created_by"]=Json::Value();
    }
    if(getCreatedOn())
    {
        ret["created_on"]=getCreatedOn()->toDbStringLocal();
    }
    else
    {
        ret["created_on"]=Json::Value();
    }
    if(getModifiedBy())
    {
        ret["modified_by"]=(Json::Int64)getValueOfModifiedBy();
    }
    else
    {
        ret["modified_by"]=Json::Value();
    }
    if(getModifiedOn())
    {
        ret["modified_on"]=getModifiedOn()->toDbStringLocal();
    }
    else
    {
        ret["modified_on"]=Json::Value();
    }
    if(getDeletedBy())
    {
        ret["deleted_by"]=(Json::Int64)getValueOfDeletedBy();
    }
    else
    {
        ret["deleted_by"]=Json::Value();
    }
    if(getDeletedOn())
    {
        ret["deleted_on"]=getDeletedOn()->toDbStringLocal();
    }
    else
    {
        ret["deleted_on"]=Json::Value();
    }
    if(getIsDelete())
    {
        ret["is_delete"]=getValueOfIsDelete();
    }
    else
    {
        ret["is_delete"]=Json::Value();
    }
    return ret;
}

bool TTreatmentDiscount::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("doctor_office_treatment_price_id"))
    {
        if(!validJsonOfField(1, "doctor_office_treatment_price_id", pJson["doctor_office_treatment_price_id"], err, true))
            return false;
    }
    if(pJson.isMember("value"))
    {
        if(!validJsonOfField(2, "value", pJson["value"], err, true))
            return false;
    }
    if(pJson.isMember("created_by"))
    {
        if(!validJsonOfField(3, "created_by", pJson["created_by"], err, true))
            return false;
    }
    else
    {
        err="The created_by column cannot be null";
        return false;
    }
    if(pJson.isMember("created_on"))
    {
        if(!validJsonOfField(4, "created_on", pJson["created_on"], err, true))
            return false;
    }
    else
    {
        err="The created_on column cannot be null";
        return false;
    }
    if(pJson.isMember("modified_by"))
    {
        if(!validJsonOfField(5, "modified_by", pJson["modified_by"], err, true))
            return false;
    }
    if(pJson.isMember("modified_on"))
    {
        if(!validJsonOfField(6, "modified_on", pJson["modified_on"], err, true))
            return false;
    }
    if(pJson.isMember("deleted_by"))
    {
        if(!validJsonOfField(7, "deleted_by", pJson["deleted_by"], err, true))
            return false;
    }
    if(pJson.isMember("deleted_on"))
    {
        if(!validJsonOfField(8, "deleted_on", pJson["deleted_on"], err, true))
            return false;
    }
    if(pJson.isMember("is_delete"))
    {
        if(!validJsonOfField(9, "is_delete", pJson["is_delete"], err, true))
            return false;
    }
    return true;
}
bool TTreatmentDiscount::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                            const std::vector<std::string> &pMasqueradingVector,
                                                            std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TTreatmentDiscount::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("doctor_office_treatment_price_id"))
    {
        if(!validJsonOfField(1, "doctor_office_treatment_price_id", pJson["doctor_office_treatment_price_id"], err, false))
            return false;
    }
    if(pJson.isMember("value"))
    {
        if(!validJsonOfField(2, "value", pJson["value"], err, false))
            return false;
    }
    if(pJson.isMember("created_by"))
    {
        if(!validJsonOfField(3, "created_by", pJson["created_by"], err, false))
            return false;
    }
    if(pJson.isMember("created_on"))
    {
        if(!validJsonOfField(4, "created_on", pJson["created_on"], err, false))
            return false;
    }
    if(pJson.isMember("modified_by"))
    {
        if(!validJsonOfField(5, "modified_by", pJson["modified_by"], err, false))
            return false;
    }
    if(pJson.isMember("modified_on"))
    {
        if(!validJsonOfField(6, "modified_on", pJson["modified_on"], err, false))
            return false;
    }
    if(pJson.isMember("deleted_by"))
    {
        if(!validJsonOfField(7, "deleted_by", pJson["deleted_by"], err, false))
            return false;
    }
    if(pJson.isMember("deleted_on"))
    {
        if(!validJsonOfField(8, "deleted_on", pJson["deleted_on"], err, false))
            return false;
    }
    if(pJson.isMember("is_delete"))
    {
        if(!validJsonOfField(9, "is_delete", pJson["is_delete"], err, false))
            return false;
    }
    return true;
}
bool TTreatmentDiscount::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                          const std::vector<std::string> &pMasqueradingVector,
                                                          std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TTreatmentDiscount::validJsonOfField(size_t index,
                                          const std::string &fieldName,
                                          const Json::Value &pJson,
                                          std::string &err,
                                          bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
